// Thai provinces & districts (เขต/อำเภอ).
// Source: https://github.com/kongvut/thai-province-data (api/latest/{province,district}.json)

export type Province = { id: number; name: string; nameEn: string };
export type District = {
  id: number;
  name: string;
  nameEn: string;
  provinceId: number;
};

/** จุฬาฯ ตั้งอยู่ที่ กรุงเทพมหานคร / เขตปทุมวัน — the final travel leg ends here. */
export const CHULA_PROVINCE_ID = 1;
export const CHULA_DISTRICT_ID = 1007;

export const PROVINCES: Province[] = [
  { id: 1, name: "กรุงเทพมหานคร", nameEn: "Bangkok" },
  { id: 2, name: "สมุทรปราการ", nameEn: "Samut Prakan" },
  { id: 3, name: "นนทบุรี", nameEn: "Nonthaburi" },
  { id: 4, name: "ปทุมธานี", nameEn: "Pathum Thani" },
  { id: 5, name: "พระนครศรีอยุธยา", nameEn: "Phra Nakhon Si Ayutthaya" },
  { id: 6, name: "อ่างทอง", nameEn: "Ang Thong" },
  { id: 7, name: "ลพบุรี", nameEn: "Lopburi" },
  { id: 8, name: "สิงห์บุรี", nameEn: "Sing Buri" },
  { id: 9, name: "ชัยนาท", nameEn: "Chai Nat" },
  { id: 10, name: "สระบุรี", nameEn: "Saraburi" },
  { id: 11, name: "ชลบุรี", nameEn: "Chon Buri" },
  { id: 12, name: "ระยอง", nameEn: "Rayong" },
  { id: 13, name: "จันทบุรี", nameEn: "Chanthaburi" },
  { id: 14, name: "ตราด", nameEn: "Trat" },
  { id: 15, name: "ฉะเชิงเทรา", nameEn: "Chachoengsao" },
  { id: 16, name: "ปราจีนบุรี", nameEn: "Prachin Buri" },
  { id: 17, name: "นครนายก", nameEn: "Nakhon Nayok" },
  { id: 18, name: "สระแก้ว", nameEn: "Sa Kaeo" },
  { id: 19, name: "นครราชสีมา", nameEn: "Nakhon Ratchasima" },
  { id: 20, name: "บุรีรัมย์", nameEn: "Buri Ram" },
  { id: 21, name: "สุรินทร์", nameEn: "Surin" },
  { id: 22, name: "ศรีสะเกษ", nameEn: "Si Sa Ket" },
  { id: 23, name: "อุบลราชธานี", nameEn: "Ubon Ratchathani" },
  { id: 24, name: "ยโสธร", nameEn: "Yasothon" },
  { id: 25, name: "ชัยภูมิ", nameEn: "Chaiyaphum" },
  { id: 26, name: "อำนาจเจริญ", nameEn: "Amnat Charoen" },
  { id: 27, name: "หนองบัวลำภู", nameEn: "Nong Bua Lam Phu" },
  { id: 28, name: "ขอนแก่น", nameEn: "Khon Kaen" },
  { id: 29, name: "อุดรธานี", nameEn: "Udon Thani" },
  { id: 30, name: "เลย", nameEn: "Loei" },
  { id: 31, name: "หนองคาย", nameEn: "Nong Khai" },
  { id: 32, name: "มหาสารคาม", nameEn: "Maha Sarakham" },
  { id: 33, name: "ร้อยเอ็ด", nameEn: "Roi Et" },
  { id: 34, name: "กาฬสินธุ์", nameEn: "Kalasin" },
  { id: 35, name: "สกลนคร", nameEn: "Sakon Nakhon" },
  { id: 36, name: "นครพนม", nameEn: "Nakhon Phanom" },
  { id: 37, name: "มุกดาหาร", nameEn: "Mukdahan" },
  { id: 38, name: "เชียงใหม่", nameEn: "Chiang Mai" },
  { id: 39, name: "ลำพูน", nameEn: "Lamphun" },
  { id: 40, name: "ลำปาง", nameEn: "Lampang" },
  { id: 41, name: "อุตรดิตถ์", nameEn: "Uttaradit" },
  { id: 42, name: "แพร่", nameEn: "Phrae" },
  { id: 43, name: "น่าน", nameEn: "Nan" },
  { id: 44, name: "พะเยา", nameEn: "Phayao" },
  { id: 45, name: "เชียงราย", nameEn: "Chiang Rai" },
  { id: 46, name: "แม่ฮ่องสอน", nameEn: "Mae Hong Son" },
  { id: 47, name: "นครสวรรค์", nameEn: "Nakhon Sawan" },
  { id: 48, name: "อุทัยธานี", nameEn: "Uthai Thani" },
  { id: 49, name: "กำแพงเพชร", nameEn: "Kamphaeng Phet" },
  { id: 50, name: "ตาก", nameEn: "Tak" },
  { id: 51, name: "สุโขทัย", nameEn: "Sukhothai" },
  { id: 52, name: "พิษณุโลก", nameEn: "Phitsanulok" },
  { id: 53, name: "พิจิตร", nameEn: "Phichit" },
  { id: 54, name: "เพชรบูรณ์", nameEn: "Phetchabun" },
  { id: 55, name: "ราชบุรี", nameEn: "Ratchaburi" },
  { id: 56, name: "กาญจนบุรี", nameEn: "Kanchanaburi" },
  { id: 57, name: "สุพรรณบุรี", nameEn: "Suphan Buri" },
  { id: 58, name: "นครปฐม", nameEn: "Nakhon Pathom" },
  { id: 59, name: "สมุทรสาคร", nameEn: "Samut Sakhon" },
  { id: 60, name: "สมุทรสงคราม", nameEn: "Samut Songkhram" },
  { id: 61, name: "เพชรบุรี", nameEn: "Phetchaburi" },
  { id: 62, name: "ประจวบคีรีขันธ์", nameEn: "Prachuap Khiri Khan" },
  { id: 63, name: "นครศรีธรรมราช", nameEn: "Nakhon Si Thammarat" },
  { id: 64, name: "กระบี่", nameEn: "Krabi" },
  { id: 65, name: "พังงา", nameEn: "Phangnga" },
  { id: 66, name: "ภูเก็ต", nameEn: "Phuket" },
  { id: 67, name: "สุราษฎร์ธานี", nameEn: "Surat Thani" },
  { id: 68, name: "ระนอง", nameEn: "Ranong" },
  { id: 69, name: "ชุมพร", nameEn: "Chumphon" },
  { id: 70, name: "สงขลา", nameEn: "Songkhla" },
  { id: 71, name: "สตูล", nameEn: "Satun" },
  { id: 72, name: "ตรัง", nameEn: "Trang" },
  { id: 73, name: "พัทลุง", nameEn: "Phatthalung" },
  { id: 74, name: "ปัตตานี", nameEn: "Pattani" },
  { id: 75, name: "ยะลา", nameEn: "Yala" },
  { id: 76, name: "นราธิวาส", nameEn: "Narathiwat" },
  { id: 77, name: "บึงกาฬ", nameEn: "Bueng Kan" },
];

export const DISTRICTS: District[] = [
  { id: 1001, name: "เขตพระนคร", nameEn: "Khet Phra Nakhon", provinceId: 1 },
  { id: 1002, name: "เขตดุสิต", nameEn: "Khet Dusit", provinceId: 1 },
  { id: 1003, name: "เขตหนองจอก", nameEn: "Khet Nong Chok", provinceId: 1 },
  { id: 1004, name: "เขตบางรัก", nameEn: "Khet Bang Rak", provinceId: 1 },
  { id: 1005, name: "เขตบางเขน", nameEn: "Khet Bang Khen", provinceId: 1 },
  { id: 1006, name: "เขตบางกะปิ", nameEn: "Khet Bang Kapi", provinceId: 1 },
  { id: 1007, name: "เขตปทุมวัน", nameEn: "Khet Pathum Wan", provinceId: 1 },
  {
    id: 1008,
    name: "เขตป้อมปราบศัตรูพ่าย",
    nameEn: "Khet Pom Prap Sattru Phai",
    provinceId: 1,
  },
  { id: 1009, name: "เขตพระโขนง", nameEn: "Khet Phra Khanong", provinceId: 1 },
  { id: 1010, name: "เขตมีนบุรี", nameEn: "Khet Min Buri", provinceId: 1 },
  { id: 1011, name: "เขตลาดกระบัง", nameEn: "Khet Lat Krabang", provinceId: 1 },
  { id: 1012, name: "เขตยานนาวา", nameEn: "Khet Yan Nawa", provinceId: 1 },
  {
    id: 1013,
    name: "เขตสัมพันธวงศ์",
    nameEn: "Khet Samphanthawong",
    provinceId: 1,
  },
  { id: 1014, name: "เขตพญาไท", nameEn: "Khet Phaya Thai", provinceId: 1 },
  { id: 1015, name: "เขตธนบุรี", nameEn: "Khet Thon Buri", provinceId: 1 },
  {
    id: 1016,
    name: "เขตบางกอกใหญ่",
    nameEn: "Khet Bangkok Yai",
    provinceId: 1,
  },
  { id: 1017, name: "เขตห้วยขวาง", nameEn: "Khet Huai Khwang", provinceId: 1 },
  { id: 1018, name: "เขตคลองสาน", nameEn: "Khet Khlong San", provinceId: 1 },
  { id: 1019, name: "เขตตลิ่งชัน", nameEn: "Khet Taling Chan", provinceId: 1 },
  {
    id: 1020,
    name: "เขตบางกอกน้อย",
    nameEn: "Khet Bangkok Noi",
    provinceId: 1,
  },
  {
    id: 1021,
    name: "เขตบางขุนเทียน",
    nameEn: "Khet Bang Khun Thian",
    provinceId: 1,
  },
  {
    id: 1022,
    name: "เขตภาษีเจริญ",
    nameEn: "Khet Phasi Charoen",
    provinceId: 1,
  },
  { id: 1023, name: "เขตหนองแขม", nameEn: "Khet Nong Khaem", provinceId: 1 },
  {
    id: 1024,
    name: "เขตราษฎร์บูรณะ",
    nameEn: "Khet Rat Burana",
    provinceId: 1,
  },
  { id: 1025, name: "เขตบางพลัด", nameEn: "Khet Bang Phlat", provinceId: 1 },
  { id: 1026, name: "เขตดินแดง", nameEn: "Khet Din Daeng", provinceId: 1 },
  { id: 1027, name: "เขตบึงกุ่ม", nameEn: "Khet Bueng Kum", provinceId: 1 },
  { id: 1028, name: "เขตสาทร", nameEn: "Khet Sathon", provinceId: 1 },
  { id: 1029, name: "เขตบางซื่อ", nameEn: "Khet Bang Sue", provinceId: 1 },
  { id: 1030, name: "เขตจตุจักร", nameEn: "Khet Chatuchak", provinceId: 1 },
  {
    id: 1031,
    name: "เขตบางคอแหลม",
    nameEn: "Khet Bang Kho Laem",
    provinceId: 1,
  },
  { id: 1032, name: "เขตประเวศ", nameEn: "Khet Prawet", provinceId: 1 },
  { id: 1033, name: "เขตคลองเตย", nameEn: "Khet Khlong Toei", provinceId: 1 },
  { id: 1034, name: "เขตสวนหลวง", nameEn: "Khet Suan Luang", provinceId: 1 },
  { id: 1035, name: "เขตจอมทอง", nameEn: "Khet Chom Thong", provinceId: 1 },
  { id: 1036, name: "เขตดอนเมือง", nameEn: "Khet Don Mueang", provinceId: 1 },
  { id: 1037, name: "เขตราชเทวี", nameEn: "Khet Ratchathewi", provinceId: 1 },
  { id: 1038, name: "เขตลาดพร้าว", nameEn: "Khet Lat Phrao", provinceId: 1 },
  { id: 1039, name: "เขตวัฒนา", nameEn: "Khet Watthana", provinceId: 1 },
  { id: 1040, name: "เขตบางแค", nameEn: "Khet Bang Khae", provinceId: 1 },
  { id: 1041, name: "เขตหลักสี่", nameEn: "Khet Lak Si", provinceId: 1 },
  { id: 1042, name: "เขตสายไหม", nameEn: "Khet Sai Mai", provinceId: 1 },
  { id: 1043, name: "เขตคันนายาว", nameEn: "Khet Khan Na Yao", provinceId: 1 },
  { id: 1044, name: "เขตสะพานสูง", nameEn: "Khet Saphan Sung", provinceId: 1 },
  {
    id: 1045,
    name: "เขตวังทองหลาง",
    nameEn: "Khet Wang Thonglang",
    provinceId: 1,
  },
  {
    id: 1046,
    name: "เขตคลองสามวา",
    nameEn: "Khet Khlong Sam Wa",
    provinceId: 1,
  },
  { id: 1047, name: "เขตบางนา", nameEn: "Khet Bang Na", provinceId: 1 },
  {
    id: 1048,
    name: "เขตทวีวัฒนา",
    nameEn: "Khet Thawi Watthana",
    provinceId: 1,
  },
  { id: 1049, name: "เขตทุ่งครุ", nameEn: "Khet Thung Khru", provinceId: 1 },
  { id: 1050, name: "เขตบางบอน", nameEn: "Khet Bang Bon", provinceId: 1 },
  {
    id: 1101,
    name: "เมืองสมุทรปราการ",
    nameEn: "Mueang Samut Prakan",
    provinceId: 2,
  },
  { id: 1102, name: "บางบ่อ", nameEn: "Bang Bo", provinceId: 2 },
  { id: 1103, name: "บางพลี", nameEn: "Bang Phli", provinceId: 2 },
  { id: 1104, name: "พระประแดง", nameEn: "Phra Pradaeng", provinceId: 2 },
  {
    id: 1105,
    name: "พระสมุทรเจดีย์",
    nameEn: "Phra Samut Chedi",
    provinceId: 2,
  },
  { id: 1106, name: "บางเสาธง", nameEn: "Bang Sao Thong", provinceId: 2 },
  {
    id: 1201,
    name: "เมืองนนทบุรี",
    nameEn: "Mueang Nonthaburi",
    provinceId: 3,
  },
  { id: 1202, name: "บางกรวย", nameEn: "Bang Kruai", provinceId: 3 },
  { id: 1203, name: "บางใหญ่", nameEn: "Bang Yai", provinceId: 3 },
  { id: 1204, name: "บางบัวทอง", nameEn: "Bang Bua Thong", provinceId: 3 },
  { id: 1205, name: "ไทรน้อย", nameEn: "Sai Noi", provinceId: 3 },
  { id: 1206, name: "ปากเกร็ด", nameEn: "Pak Kret", provinceId: 3 },
  {
    id: 1301,
    name: "เมืองปทุมธานี",
    nameEn: "Mueang Pathum Thani",
    provinceId: 4,
  },
  { id: 1302, name: "คลองหลวง", nameEn: "Khlong Luang", provinceId: 4 },
  { id: 1303, name: "ธัญบุรี", nameEn: "Thanyaburi", provinceId: 4 },
  { id: 1304, name: "หนองเสือ", nameEn: "Nong Suea", provinceId: 4 },
  { id: 1305, name: "ลาดหลุมแก้ว", nameEn: "Lat Lum Kaeo", provinceId: 4 },
  { id: 1306, name: "ลำลูกกา", nameEn: "Lam Luk Ka", provinceId: 4 },
  { id: 1307, name: "สามโคก", nameEn: "Sam Khok", provinceId: 4 },
  {
    id: 1401,
    name: "พระนครศรีอยุธยา",
    nameEn: "Phra Nakhon Si Ayutthaya",
    provinceId: 5,
  },
  { id: 1402, name: "ท่าเรือ", nameEn: "Tha Ruea", provinceId: 5 },
  { id: 1403, name: "นครหลวง", nameEn: "Nakhon Luang", provinceId: 5 },
  { id: 1404, name: "บางไทร", nameEn: "Bang Sai", provinceId: 5 },
  { id: 1405, name: "บางบาล", nameEn: "Bang Ban", provinceId: 5 },
  { id: 1406, name: "บางปะอิน", nameEn: "Bang Pa-in", provinceId: 5 },
  { id: 1407, name: "บางปะหัน", nameEn: "Bang Pahan", provinceId: 5 },
  { id: 1408, name: "ผักไห่", nameEn: "Phak Hai", provinceId: 5 },
  { id: 1409, name: "ภาชี", nameEn: "Phachi", provinceId: 5 },
  { id: 1410, name: "ลาดบัวหลวง", nameEn: "Lat Bua Luang", provinceId: 5 },
  { id: 1411, name: "วังน้อย", nameEn: "Wang Noi", provinceId: 5 },
  { id: 1412, name: "เสนา", nameEn: "Sena", provinceId: 5 },
  { id: 1413, name: "บางซ้าย", nameEn: "Bang Sai", provinceId: 5 },
  { id: 1414, name: "อุทัย", nameEn: "Uthai", provinceId: 5 },
  { id: 1415, name: "มหาราช", nameEn: "Maha Rat", provinceId: 5 },
  { id: 1416, name: "บ้านแพรก", nameEn: "Ban Phraek", provinceId: 5 },
  { id: 1501, name: "เมืองอ่างทอง", nameEn: "Mueang Ang Thong", provinceId: 6 },
  { id: 1502, name: "ไชโย", nameEn: "Chaiyo", provinceId: 6 },
  { id: 1503, name: "ป่าโมก", nameEn: "Pa Mok", provinceId: 6 },
  { id: 1504, name: "โพธิ์ทอง", nameEn: "Pho Thong", provinceId: 6 },
  { id: 1505, name: "แสวงหา", nameEn: "Sawaeng Ha", provinceId: 6 },
  { id: 1506, name: "วิเศษชัยชาญ", nameEn: "Wiset Chai Chan", provinceId: 6 },
  { id: 1507, name: "สามโก้", nameEn: "Samko", provinceId: 6 },
  { id: 1601, name: "เมืองลพบุรี", nameEn: "Mueang Lop Buri", provinceId: 7 },
  { id: 1602, name: "พัฒนานิคม", nameEn: "Phatthana Nikhom", provinceId: 7 },
  { id: 1603, name: "โคกสำโรง", nameEn: "Khok Samrong", provinceId: 7 },
  { id: 1604, name: "ชัยบาดาล", nameEn: "Chai Badan", provinceId: 7 },
  { id: 1605, name: "ท่าวุ้ง", nameEn: "Tha Wung", provinceId: 7 },
  { id: 1606, name: "บ้านหมี่", nameEn: "Ban Mi", provinceId: 7 },
  { id: 1607, name: "ท่าหลวง", nameEn: "Tha Luang", provinceId: 7 },
  { id: 1608, name: "สระโบสถ์", nameEn: "Sa Bot", provinceId: 7 },
  { id: 1609, name: "โคกเจริญ", nameEn: "Khok Charoen", provinceId: 7 },
  { id: 1610, name: "ลำสนธิ", nameEn: "Lam Sonthi", provinceId: 7 },
  { id: 1611, name: "หนองม่วง", nameEn: "Nong Muang", provinceId: 7 },
  {
    id: 1701,
    name: "เมืองสิงห์บุรี",
    nameEn: "Mueang Sing Buri",
    provinceId: 8,
  },
  { id: 1702, name: "บางระจัน", nameEn: "Bang Rachan", provinceId: 8 },
  { id: 1703, name: "ค่ายบางระจัน", nameEn: "Khai Bang Rachan", provinceId: 8 },
  { id: 1704, name: "พรหมบุรี", nameEn: "Phrom Buri", provinceId: 8 },
  { id: 1705, name: "ท่าช้าง", nameEn: "Tha Chang", provinceId: 8 },
  { id: 1706, name: "อินทร์บุรี", nameEn: "In Buri", provinceId: 8 },
  { id: 1801, name: "เมืองชัยนาท", nameEn: "Mueang Chai Nat", provinceId: 9 },
  { id: 1802, name: "มโนรมย์", nameEn: "Manorom", provinceId: 9 },
  { id: 1803, name: "วัดสิงห์", nameEn: "Wat Sing", provinceId: 9 },
  { id: 1804, name: "สรรพยา", nameEn: "Sapphaya", provinceId: 9 },
  { id: 1805, name: "สรรคบุรี", nameEn: "Sankhaburi", provinceId: 9 },
  { id: 1806, name: "หันคา", nameEn: "Hankha", provinceId: 9 },
  { id: 1807, name: "หนองมะโมง", nameEn: "Nong Mamong", provinceId: 9 },
  { id: 1808, name: "เนินขาม", nameEn: "Noen Kham", provinceId: 9 },
  { id: 1901, name: "เมืองสระบุรี", nameEn: "Mueang Saraburi", provinceId: 10 },
  { id: 1902, name: "แก่งคอย", nameEn: "Kaeng Khoi", provinceId: 10 },
  { id: 1903, name: "หนองแค", nameEn: "Nong Khae", provinceId: 10 },
  { id: 1904, name: "วิหารแดง", nameEn: "Wihan Daeng", provinceId: 10 },
  { id: 1905, name: "หนองแซง", nameEn: "Nong Saeng", provinceId: 10 },
  { id: 1906, name: "บ้านหมอ", nameEn: "Ban Mo", provinceId: 10 },
  { id: 1907, name: "ดอนพุด", nameEn: "Don Phut", provinceId: 10 },
  { id: 1908, name: "หนองโดน", nameEn: "Nong Don", provinceId: 10 },
  { id: 1909, name: "พระพุทธบาท", nameEn: "Phra Phutthabat", provinceId: 10 },
  { id: 1910, name: "เสาไห้", nameEn: "Sao Hai", provinceId: 10 },
  { id: 1911, name: "มวกเหล็ก", nameEn: "Muak Lek", provinceId: 10 },
  { id: 1912, name: "วังม่วง", nameEn: "Wang Muang", provinceId: 10 },
  {
    id: 1913,
    name: "เฉลิมพระเกียรติ",
    nameEn: "Chaloem Phra Kiat",
    provinceId: 10,
  },
  { id: 2001, name: "เมืองชลบุรี", nameEn: "Mueang Chon Buri", provinceId: 11 },
  { id: 2002, name: "บ้านบึง", nameEn: "Ban Bueng", provinceId: 11 },
  { id: 2003, name: "หนองใหญ่", nameEn: "Nong Yai", provinceId: 11 },
  { id: 2004, name: "บางละมุง", nameEn: "Bang Lamung", provinceId: 11 },
  { id: 2005, name: "พานทอง", nameEn: "Phan Thong", provinceId: 11 },
  { id: 2006, name: "พนัสนิคม", nameEn: "Phanat Nikhom", provinceId: 11 },
  { id: 2007, name: "ศรีราชา", nameEn: "Si Racha", provinceId: 11 },
  { id: 2008, name: "เกาะสีชัง", nameEn: "Ko Sichang", provinceId: 11 },
  { id: 2009, name: "สัตหีบ", nameEn: "Sattahip", provinceId: 11 },
  { id: 2010, name: "บ่อทอง", nameEn: "Bo Thong", provinceId: 11 },
  { id: 2011, name: "เกาะจันทร์", nameEn: "Ko Chan", provinceId: 11 },
  { id: 2101, name: "เมืองระยอง", nameEn: "Mueang Rayong", provinceId: 12 },
  { id: 2102, name: "บ้านฉาง", nameEn: "Ban Chang", provinceId: 12 },
  { id: 2103, name: "แกลง", nameEn: "Klaeng", provinceId: 12 },
  { id: 2104, name: "วังจันทร์", nameEn: "Wang Chan", provinceId: 12 },
  { id: 2105, name: "บ้านค่าย", nameEn: "Ban Khai", provinceId: 12 },
  { id: 2106, name: "ปลวกแดง", nameEn: "Pluak Daeng", provinceId: 12 },
  { id: 2107, name: "เขาชะเมา", nameEn: "Khao Chamao", provinceId: 12 },
  { id: 2108, name: "นิคมพัฒนา", nameEn: "Nikhom Phatthana", provinceId: 12 },
  {
    id: 2201,
    name: "เมืองจันทบุรี",
    nameEn: "Mueang Chanthaburi",
    provinceId: 13,
  },
  { id: 2202, name: "ขลุง", nameEn: "Khlung", provinceId: 13 },
  { id: 2203, name: "ท่าใหม่", nameEn: "Tha Mai", provinceId: 13 },
  { id: 2204, name: "โป่งน้ำร้อน", nameEn: "Pong Nam Ron", provinceId: 13 },
  { id: 2205, name: "มะขาม", nameEn: "Makham", provinceId: 13 },
  { id: 2206, name: "แหลมสิงห์", nameEn: "Laem Sing", provinceId: 13 },
  { id: 2207, name: "สอยดาว", nameEn: "Soi Dao", provinceId: 13 },
  { id: 2208, name: "แก่งหางแมว", nameEn: "Kaeng Hang Maeo", provinceId: 13 },
  { id: 2209, name: "นายายอาม", nameEn: "Na Yai Am", provinceId: 13 },
  { id: 2210, name: "เขาคิชฌกูฏ", nameEn: "Khao Khitchakut", provinceId: 13 },
  { id: 2301, name: "เมืองตราด", nameEn: "Mueang Trat", provinceId: 14 },
  { id: 2302, name: "คลองใหญ่", nameEn: "Khlong Yai", provinceId: 14 },
  { id: 2303, name: "เขาสมิง", nameEn: "Khao Saming", provinceId: 14 },
  { id: 2304, name: "บ่อไร่", nameEn: "Bo Rai", provinceId: 14 },
  { id: 2305, name: "แหลมงอบ", nameEn: "Laem Ngop", provinceId: 14 },
  { id: 2306, name: "เกาะกูด", nameEn: "Ko Kut", provinceId: 14 },
  { id: 2307, name: "เกาะช้าง", nameEn: "Ko Chang", provinceId: 14 },
  {
    id: 2401,
    name: "เมืองฉะเชิงเทรา",
    nameEn: "Mueang Chachoengsao",
    provinceId: 15,
  },
  { id: 2402, name: "บางคล้า", nameEn: "Bang Khla", provinceId: 15 },
  { id: 2403, name: "บางน้ำเปรี้ยว", nameEn: "Bang Nam Priao", provinceId: 15 },
  { id: 2404, name: "บางปะกง", nameEn: "Bang Pakong", provinceId: 15 },
  { id: 2405, name: "บ้านโพธิ์", nameEn: "Ban Pho", provinceId: 15 },
  { id: 2406, name: "พนมสารคาม", nameEn: "Phanom Sarakham", provinceId: 15 },
  { id: 2407, name: "ราชสาส์น", nameEn: "Ratchasan", provinceId: 15 },
  { id: 2408, name: "สนามชัยเขต", nameEn: "Sanam Chai Khet", provinceId: 15 },
  { id: 2409, name: "แปลงยาว", nameEn: "Plaeng Yao", provinceId: 15 },
  { id: 2410, name: "ท่าตะเกียบ", nameEn: "Tha Takiap", provinceId: 15 },
  { id: 2411, name: "คลองเขื่อน", nameEn: "Khlong Khuean", provinceId: 15 },
  {
    id: 2501,
    name: "เมืองปราจีนบุรี",
    nameEn: "Mueang Prachin Buri",
    provinceId: 16,
  },
  { id: 2502, name: "กบินทร์บุรี", nameEn: "Kabin Buri", provinceId: 16 },
  { id: 2503, name: "นาดี", nameEn: "Na Di", provinceId: 16 },
  { id: 2506, name: "บ้านสร้าง", nameEn: "Ban Sang", provinceId: 16 },
  { id: 2507, name: "ประจันตคาม", nameEn: "Prachantakham", provinceId: 16 },
  { id: 2508, name: "ศรีมหาโพธิ", nameEn: "Si Maha Phot", provinceId: 16 },
  { id: 2509, name: "ศรีมโหสถ", nameEn: "Si Mahosot", provinceId: 16 },
  {
    id: 2601,
    name: "เมืองนครนายก",
    nameEn: "Mueang Nakhon Nayok",
    provinceId: 17,
  },
  { id: 2602, name: "ปากพลี", nameEn: "Pak Phli", provinceId: 17 },
  { id: 2603, name: "บ้านนา", nameEn: "Ban Na", provinceId: 17 },
  { id: 2604, name: "องครักษ์", nameEn: "Ongkharak", provinceId: 17 },
  { id: 2701, name: "เมืองสระแก้ว", nameEn: "Mueang Sa Kaeo", provinceId: 18 },
  { id: 2702, name: "คลองหาด", nameEn: "Khlong Hat", provinceId: 18 },
  { id: 2703, name: "ตาพระยา", nameEn: "Ta Phraya", provinceId: 18 },
  { id: 2704, name: "วังน้ำเย็น", nameEn: "Wang Nam Yen", provinceId: 18 },
  { id: 2705, name: "วัฒนานคร", nameEn: "Watthana Nakhon", provinceId: 18 },
  { id: 2706, name: "อรัญประเทศ", nameEn: "Aranyaprathet", provinceId: 18 },
  { id: 2707, name: "เขาฉกรรจ์", nameEn: "Khao Chakan", provinceId: 18 },
  { id: 2708, name: "โคกสูง", nameEn: "Khok Sung", provinceId: 18 },
  { id: 2709, name: "วังสมบูรณ์", nameEn: "Wang Sombun", provinceId: 18 },
  {
    id: 3001,
    name: "เมืองนครราชสีมา",
    nameEn: "Mueang Nakhon Ratchasima",
    provinceId: 19,
  },
  { id: 3002, name: "ครบุรี", nameEn: "Khon Buri", provinceId: 19 },
  { id: 3003, name: "เสิงสาง", nameEn: "Soeng Sang", provinceId: 19 },
  { id: 3004, name: "คง", nameEn: "Khong", provinceId: 19 },
  { id: 3005, name: "บ้านเหลื่อม", nameEn: "Ban Lueam", provinceId: 19 },
  { id: 3006, name: "จักราช", nameEn: "Chakkarat", provinceId: 19 },
  { id: 3007, name: "โชคชัย", nameEn: "Chok Chai", provinceId: 19 },
  { id: 3008, name: "ด่านขุนทด", nameEn: "Dan Khun Thot", provinceId: 19 },
  { id: 3009, name: "โนนไทย", nameEn: "Non Thai", provinceId: 19 },
  { id: 3010, name: "โนนสูง", nameEn: "Non Sung", provinceId: 19 },
  { id: 3011, name: "ขามสะแกแสง", nameEn: "Kham Sakaesaeng", provinceId: 19 },
  { id: 3012, name: "บัวใหญ่", nameEn: "Bua Yai", provinceId: 19 },
  { id: 3013, name: "ประทาย", nameEn: "Prathai", provinceId: 19 },
  { id: 3014, name: "ปักธงชัย", nameEn: "Pak Thong Chai", provinceId: 19 },
  { id: 3015, name: "พิมาย", nameEn: "Phimai", provinceId: 19 },
  { id: 3016, name: "ห้วยแถลง", nameEn: "Huai Thalaeng", provinceId: 19 },
  { id: 3017, name: "ชุมพวง", nameEn: "Chum Phuang", provinceId: 19 },
  { id: 3018, name: "สูงเนิน", nameEn: "Sung Noen", provinceId: 19 },
  { id: 3019, name: "ขามทะเลสอ", nameEn: "Kham Thale So", provinceId: 19 },
  { id: 3020, name: "สีคิ้ว", nameEn: "Sikhio", provinceId: 19 },
  { id: 3021, name: "ปากช่อง", nameEn: "Pak Chong", provinceId: 19 },
  { id: 3022, name: "หนองบุญมาก", nameEn: "Nong Bun Mak", provinceId: 19 },
  { id: 3023, name: "แก้งสนามนาง", nameEn: "Kaeng Sanam Nang", provinceId: 19 },
  { id: 3024, name: "โนนแดง", nameEn: "Non Daeng", provinceId: 19 },
  { id: 3025, name: "วังน้ำเขียว", nameEn: "Wang Nam Khiao", provinceId: 19 },
  { id: 3026, name: "เทพารักษ์", nameEn: "Thepharak", provinceId: 19 },
  { id: 3027, name: "เมืองยาง", nameEn: "Mueang Yang", provinceId: 19 },
  { id: 3028, name: "พระทองคำ", nameEn: "Phra Thong Kham", provinceId: 19 },
  { id: 3029, name: "ลำทะเมนชัย", nameEn: "Lam Thamenchai", provinceId: 19 },
  { id: 3030, name: "บัวลาย", nameEn: "Bua Lai", provinceId: 19 },
  { id: 3031, name: "สีดา", nameEn: "Sida", provinceId: 19 },
  {
    id: 3032,
    name: "เฉลิมพระเกียรติ",
    nameEn: "Chaloem Phra Kiat",
    provinceId: 19,
  },
  {
    id: 3101,
    name: "เมืองบุรีรัมย์",
    nameEn: "Mueang Buri Ram",
    provinceId: 20,
  },
  { id: 3102, name: "คูเมือง", nameEn: "Khu Mueang", provinceId: 20 },
  { id: 3103, name: "กระสัง", nameEn: "Krasang", provinceId: 20 },
  { id: 3104, name: "นางรอง", nameEn: "Nang Rong", provinceId: 20 },
  { id: 3105, name: "หนองกี่", nameEn: "Nong Ki", provinceId: 20 },
  { id: 3106, name: "ละหานทราย", nameEn: "Lahan Sai", provinceId: 20 },
  { id: 3107, name: "ประโคนชัย", nameEn: "Prakhon Chai", provinceId: 20 },
  { id: 3108, name: "บ้านกรวด", nameEn: "Ban Kruat", provinceId: 20 },
  { id: 3109, name: "พุทไธสง", nameEn: "Phutthaisong", provinceId: 20 },
  { id: 3110, name: "ลำปลายมาศ", nameEn: "Lam Plai Mat", provinceId: 20 },
  { id: 3111, name: "สตึก", nameEn: "Satuek", provinceId: 20 },
  { id: 3112, name: "ปะคำ", nameEn: "Pakham", provinceId: 20 },
  { id: 3113, name: "นาโพธิ์", nameEn: "Na Pho", provinceId: 20 },
  { id: 3114, name: "หนองหงส์", nameEn: "Nong Hong", provinceId: 20 },
  { id: 3115, name: "พลับพลาชัย", nameEn: "Phlapphla Chai", provinceId: 20 },
  { id: 3116, name: "ห้วยราช", nameEn: "Huai Rat", provinceId: 20 },
  { id: 3117, name: "โนนสุวรรณ", nameEn: "Non Suwan", provinceId: 20 },
  { id: 3118, name: "ชำนิ", nameEn: "Chamni", provinceId: 20 },
  {
    id: 3119,
    name: "บ้านใหม่ไชยพจน์",
    nameEn: "Ban Mai Chaiyaphot",
    provinceId: 20,
  },
  { id: 3120, name: "โนนดินแดง", nameEn: "Non Din Daeng", provinceId: 20 },
  { id: 3121, name: "บ้านด่าน", nameEn: "Ban Dan", provinceId: 20 },
  { id: 3122, name: "แคนดง", nameEn: "Khaen Dong", provinceId: 20 },
  {
    id: 3123,
    name: "เฉลิมพระเกียรติ",
    nameEn: "Chaloem Phra Kiat",
    provinceId: 20,
  },
  { id: 3201, name: "เมืองสุรินทร์", nameEn: "Mueang Surin", provinceId: 21 },
  { id: 3202, name: "ชุมพลบุรี", nameEn: "Chumphon Buri", provinceId: 21 },
  { id: 3203, name: "ท่าตูม", nameEn: "Tha Tum", provinceId: 21 },
  { id: 3204, name: "จอมพระ", nameEn: "Chom Phra", provinceId: 21 },
  { id: 3205, name: "ปราสาท", nameEn: "Prasat", provinceId: 21 },
  { id: 3206, name: "กาบเชิง", nameEn: "Kap Choeng", provinceId: 21 },
  { id: 3207, name: "รัตนบุรี", nameEn: "Rattanaburi", provinceId: 21 },
  { id: 3208, name: "สนม", nameEn: "Sanom", provinceId: 21 },
  { id: 3209, name: "ศีขรภูมิ", nameEn: "Sikhoraphum", provinceId: 21 },
  { id: 3210, name: "สังขะ", nameEn: "Sangkha", provinceId: 21 },
  { id: 3211, name: "ลำดวน", nameEn: "Lamduan", provinceId: 21 },
  { id: 3212, name: "สำโรงทาบ", nameEn: "Samrong Thap", provinceId: 21 },
  { id: 3213, name: "บัวเชด", nameEn: "Buachet", provinceId: 21 },
  { id: 3214, name: "พนมดงรัก", nameEn: "Phanom Dong Rak", provinceId: 21 },
  { id: 3215, name: "ศรีณรงค์", nameEn: "Si Narong", provinceId: 21 },
  { id: 3216, name: "เขวาสินรินทร์", nameEn: "Khwao Sinarin", provinceId: 21 },
  { id: 3217, name: "โนนนารายณ์", nameEn: "Non Narai", provinceId: 21 },
  {
    id: 3301,
    name: "เมืองศรีสะเกษ",
    nameEn: "Mueang Si Sa Ket",
    provinceId: 22,
  },
  { id: 3302, name: "ยางชุมน้อย", nameEn: "Yang Chum Noi", provinceId: 22 },
  { id: 3303, name: "กันทรารมย์", nameEn: "Kanthararom", provinceId: 22 },
  { id: 3304, name: "กันทรลักษ์", nameEn: "Kantharalak", provinceId: 22 },
  { id: 3305, name: "ขุขันธ์", nameEn: "Khukhan", provinceId: 22 },
  { id: 3306, name: "ไพรบึง", nameEn: "Phrai Bueng", provinceId: 22 },
  { id: 3307, name: "ปรางค์กู่", nameEn: "Prang Ku", provinceId: 22 },
  { id: 3308, name: "ขุนหาญ", nameEn: "Khun Han", provinceId: 22 },
  { id: 3309, name: "ราษีไศล", nameEn: "Rasi Salai", provinceId: 22 },
  {
    id: 3310,
    name: "อุทุมพรพิสัย",
    nameEn: "Uthumphon Phisai",
    provinceId: 22,
  },
  { id: 3311, name: "บึงบูรพ์", nameEn: "Bueng Bun", provinceId: 22 },
  { id: 3312, name: "ห้วยทับทัน", nameEn: "Huai Thap Than", provinceId: 22 },
  { id: 3313, name: "โนนคูณ", nameEn: "Non Khun", provinceId: 22 },
  { id: 3314, name: "ศรีรัตนะ", nameEn: "Si Rattana", provinceId: 22 },
  { id: 3315, name: "น้ำเกลี้ยง", nameEn: "Nam Kliang", provinceId: 22 },
  { id: 3316, name: "วังหิน", nameEn: "Wang Hin", provinceId: 22 },
  { id: 3317, name: "ภูสิงห์", nameEn: "Phu Sing", provinceId: 22 },
  { id: 3318, name: "เมืองจันทร์", nameEn: "Mueang Chan", provinceId: 22 },
  { id: 3319, name: "เบญจลักษ์", nameEn: "Benchalak", provinceId: 22 },
  { id: 3320, name: "พยุห์", nameEn: "Phayu", provinceId: 22 },
  { id: 3321, name: "โพธิ์ศรีสุวรรณ", nameEn: "Pho Si Suwan", provinceId: 22 },
  { id: 3322, name: "ศิลาลาด", nameEn: "Sila Lat", provinceId: 22 },
  {
    id: 3401,
    name: "เมืองอุบลราชธานี",
    nameEn: "Mueang Ubon Ratchathani",
    provinceId: 23,
  },
  { id: 3402, name: "ศรีเมืองใหม่", nameEn: "Si Mueang Mai", provinceId: 23 },
  { id: 3403, name: "โขงเจียม", nameEn: "Khong Chiam", provinceId: 23 },
  { id: 3404, name: "เขื่องใน", nameEn: "Khueang Nai", provinceId: 23 },
  { id: 3405, name: "เขมราฐ", nameEn: "Khemarat", provinceId: 23 },
  { id: 3407, name: "เดชอุดม", nameEn: "Det Udom", provinceId: 23 },
  { id: 3408, name: "นาจะหลวย", nameEn: "Na Chaluai", provinceId: 23 },
  { id: 3409, name: "น้ำยืน", nameEn: "Nam Yuen", provinceId: 23 },
  { id: 3410, name: "บุณฑริก", nameEn: "Buntharik", provinceId: 23 },
  {
    id: 3411,
    name: "ตระการพืชผล",
    nameEn: "Trakan Phuet Phon",
    provinceId: 23,
  },
  { id: 3412, name: "กุดข้าวปุ้น", nameEn: "Kut Khaopun", provinceId: 23 },
  { id: 3414, name: "ม่วงสามสิบ", nameEn: "Muang Sam Sip", provinceId: 23 },
  { id: 3415, name: "วารินชำราบ", nameEn: "Warin Chamrap", provinceId: 23 },
  {
    id: 3419,
    name: "พิบูลมังสาหาร",
    nameEn: "Phibun Mangsahan",
    provinceId: 23,
  },
  { id: 3420, name: "ตาลสุม", nameEn: "Tan Sum", provinceId: 23 },
  { id: 3421, name: "โพธิ์ไทร", nameEn: "Pho Sai", provinceId: 23 },
  { id: 3422, name: "สำโรง", nameEn: "Samrong", provinceId: 23 },
  { id: 3424, name: "ดอนมดแดง", nameEn: "Don Mot Daeng", provinceId: 23 },
  { id: 3425, name: "สิรินธร", nameEn: "Sirindhorn", provinceId: 23 },
  { id: 3426, name: "ทุ่งศรีอุดม", nameEn: "Thung Si Udom", provinceId: 23 },
  { id: 3429, name: "นาเยีย", nameEn: "Na Yia", provinceId: 23 },
  { id: 3430, name: "นาตาล", nameEn: "Na Tan", provinceId: 23 },
  { id: 3431, name: "เหล่าเสือโก้ก", nameEn: "Lao Suea Kok", provinceId: 23 },
  {
    id: 3432,
    name: "สว่างวีระวงศ์",
    nameEn: "Sawang Wirawong",
    provinceId: 23,
  },
  { id: 3433, name: "น้ำขุ่น", nameEn: "Nam Khun", provinceId: 23 },
  { id: 3501, name: "เมืองยโสธร", nameEn: "Mueang Yasothon", provinceId: 24 },
  { id: 3502, name: "ทรายมูล", nameEn: "Sai Mun", provinceId: 24 },
  { id: 3503, name: "กุดชุม", nameEn: "Kut Chum", provinceId: 24 },
  {
    id: 3504,
    name: "คำเขื่อนแก้ว",
    nameEn: "Kham Khuean Kaeo",
    provinceId: 24,
  },
  { id: 3505, name: "ป่าติ้ว", nameEn: "Pa Tio", provinceId: 24 },
  { id: 3506, name: "มหาชนะชัย", nameEn: "Maha Chana Chai", provinceId: 24 },
  { id: 3507, name: "ค้อวัง", nameEn: "Kho Wang", provinceId: 24 },
  { id: 3508, name: "เลิงนกทา", nameEn: "Loeng Nok Tha", provinceId: 24 },
  { id: 3509, name: "ไทยเจริญ", nameEn: "Thai Charoen", provinceId: 24 },
  {
    id: 3601,
    name: "เมืองชัยภูมิ",
    nameEn: "Mueang Chaiyaphum",
    provinceId: 25,
  },
  { id: 3602, name: "บ้านเขว้า", nameEn: "Ban Khwao", provinceId: 25 },
  { id: 3603, name: "คอนสวรรค์", nameEn: "Khon Sawan", provinceId: 25 },
  { id: 3604, name: "เกษตรสมบูรณ์", nameEn: "Kaset Sombun", provinceId: 25 },
  { id: 3605, name: "หนองบัวแดง", nameEn: "Nong Bua Daeng", provinceId: 25 },
  { id: 3606, name: "จัตุรัส", nameEn: "Chatturat", provinceId: 25 },
  { id: 3607, name: "บำเหน็จณรงค์", nameEn: "Bamnet Narong", provinceId: 25 },
  { id: 3608, name: "หนองบัวระเหว", nameEn: "Nong Bua Rawe", provinceId: 25 },
  { id: 3609, name: "เทพสถิต", nameEn: "Thep Sathit", provinceId: 25 },
  { id: 3610, name: "ภูเขียว", nameEn: "Phu Khiao", provinceId: 25 },
  { id: 3611, name: "บ้านแท่น", nameEn: "Ban Thaen", provinceId: 25 },
  { id: 3612, name: "แก้งคร้อ", nameEn: "Kaeng Khro", provinceId: 25 },
  { id: 3613, name: "คอนสาร", nameEn: "Khon San", provinceId: 25 },
  { id: 3614, name: "ภักดีชุมพล", nameEn: "Phakdi Chumphon", provinceId: 25 },
  { id: 3615, name: "เนินสง่า", nameEn: "Noen Sa-nga", provinceId: 25 },
  { id: 3616, name: "ซับใหญ่", nameEn: "Sap Yai", provinceId: 25 },
  {
    id: 3701,
    name: "เมืองอำนาจเจริญ",
    nameEn: "Mueang Amnat Charoen",
    provinceId: 26,
  },
  { id: 3702, name: "ชานุมาน", nameEn: "Chanuman", provinceId: 26 },
  {
    id: 3703,
    name: "ปทุมราชวงศา",
    nameEn: "Pathum Ratchawongsa",
    provinceId: 26,
  },
  { id: 3704, name: "พนา", nameEn: "Phana", provinceId: 26 },
  { id: 3705, name: "เสนางคนิคม", nameEn: "Senangkhanikhom", provinceId: 26 },
  { id: 3706, name: "หัวตะพาน", nameEn: "Hua Taphan", provinceId: 26 },
  { id: 3707, name: "ลืออำนาจ", nameEn: "Lue Amnat", provinceId: 26 },
  { id: 3801, name: "เมืองบึงกาฬ", nameEn: "Mueang Bueng Kan", provinceId: 77 },
  { id: 3802, name: "เซกา", nameEn: "Seka", provinceId: 77 },
  { id: 3803, name: "โซ่พิสัย", nameEn: "So Phisai", provinceId: 77 },
  { id: 3804, name: "พรเจริญ", nameEn: "Phon Charoen", provinceId: 77 },
  { id: 3805, name: "ศรีวิไล", nameEn: "Si Wilai", provinceId: 77 },
  { id: 3806, name: "บึงโขงหลง", nameEn: "Bueng Khong Long", provinceId: 77 },
  { id: 3807, name: "ปากคาด", nameEn: "Pak Khat", provinceId: 77 },
  { id: 3808, name: "บุ่งคล้า", nameEn: "Bung Khla", provinceId: 77 },
  {
    id: 3901,
    name: "เมืองหนองบัวลำภู",
    nameEn: "Mueang Nong Bua Lam Phu",
    provinceId: 27,
  },
  { id: 3902, name: "นากลาง", nameEn: "Na Klang", provinceId: 27 },
  { id: 3903, name: "โนนสัง", nameEn: "Non Sang", provinceId: 27 },
  { id: 3904, name: "ศรีบุญเรือง", nameEn: "Si Bun Rueang", provinceId: 27 },
  { id: 3905, name: "สุวรรณคูหา", nameEn: "Suwannakhuha", provinceId: 27 },
  { id: 3906, name: "นาวัง", nameEn: "Na Wang", provinceId: 27 },
  {
    id: 4001,
    name: "เมืองขอนแก่น",
    nameEn: "Mueang Khon Kaen",
    provinceId: 28,
  },
  { id: 4002, name: "บ้านฝาง", nameEn: "Ban Fang", provinceId: 28 },
  { id: 4003, name: "พระยืน", nameEn: "Phra Yuen", provinceId: 28 },
  { id: 4004, name: "หนองเรือ", nameEn: "Nong Ruea", provinceId: 28 },
  { id: 4005, name: "ชุมแพ", nameEn: "Chum Phae", provinceId: 28 },
  { id: 4006, name: "สีชมพู", nameEn: "Si Chomphu", provinceId: 28 },
  { id: 4007, name: "น้ำพอง", nameEn: "Nam Phong", provinceId: 28 },
  { id: 4008, name: "อุบลรัตน์", nameEn: "Ubolratana", provinceId: 28 },
  { id: 4009, name: "กระนวน", nameEn: "Kranuan", provinceId: 28 },
  { id: 4010, name: "บ้านไผ่", nameEn: "Ban Phai", provinceId: 28 },
  { id: 4011, name: "เปือยน้อย", nameEn: "Pueai Noi", provinceId: 28 },
  { id: 4012, name: "พล", nameEn: "Phon", provinceId: 28 },
  { id: 4013, name: "แวงใหญ่", nameEn: "Waeng Yai", provinceId: 28 },
  { id: 4014, name: "แวงน้อย", nameEn: "Waeng Noi", provinceId: 28 },
  { id: 4015, name: "หนองสองห้อง", nameEn: "Nong Song Hong", provinceId: 28 },
  { id: 4016, name: "ภูเวียง", nameEn: "Phu Wiang", provinceId: 28 },
  { id: 4017, name: "มัญจาคีรี", nameEn: "Mancha Khiri", provinceId: 28 },
  { id: 4018, name: "ชนบท", nameEn: "Chonnabot", provinceId: 28 },
  { id: 4019, name: "เขาสวนกวาง", nameEn: "Khao Suan Kwang", provinceId: 28 },
  { id: 4020, name: "ภูผาม่าน", nameEn: "Phu Pha Man", provinceId: 28 },
  { id: 4021, name: "ซำสูง", nameEn: "Sam Sung", provinceId: 28 },
  { id: 4022, name: "โคกโพธิ์ไชย", nameEn: "Khok Pho Chai", provinceId: 28 },
  { id: 4023, name: "หนองนาคำ", nameEn: "Nong Na Kham", provinceId: 28 },
  { id: 4024, name: "บ้านแฮด", nameEn: "Ban Haet", provinceId: 28 },
  { id: 4025, name: "โนนศิลา", nameEn: "Non Sila", provinceId: 28 },
  { id: 4029, name: "เวียงเก่า", nameEn: "Wiang Kao", provinceId: 28 },
  {
    id: 4101,
    name: "เมืองอุดรธานี",
    nameEn: "Mueang Udon Thani",
    provinceId: 29,
  },
  { id: 4102, name: "กุดจับ", nameEn: "Kut Chap", provinceId: 29 },
  { id: 4103, name: "หนองวัวซอ", nameEn: "Nong Wua So", provinceId: 29 },
  { id: 4104, name: "กุมภวาปี", nameEn: "Kumphawapi", provinceId: 29 },
  { id: 4105, name: "โนนสะอาด", nameEn: "Non Sa-at", provinceId: 29 },
  { id: 4106, name: "หนองหาน", nameEn: "Nong Han", provinceId: 29 },
  { id: 4107, name: "ทุ่งฝน", nameEn: "Thung Fon", provinceId: 29 },
  { id: 4108, name: "ไชยวาน", nameEn: "Chai Wan", provinceId: 29 },
  { id: 4109, name: "ศรีธาตุ", nameEn: "Si That", provinceId: 29 },
  { id: 4110, name: "วังสามหมอ", nameEn: "Wang Sam Mo", provinceId: 29 },
  { id: 4111, name: "บ้านดุง", nameEn: "Ban Dung", provinceId: 29 },
  { id: 4117, name: "บ้านผือ", nameEn: "Ban Phue", provinceId: 29 },
  { id: 4118, name: "น้ำโสม", nameEn: "Nam Som", provinceId: 29 },
  { id: 4119, name: "เพ็ญ", nameEn: "Phen", provinceId: 29 },
  { id: 4120, name: "สร้างคอม", nameEn: "Sang Khom", provinceId: 29 },
  { id: 4121, name: "หนองแสง", nameEn: "Nong Saeng", provinceId: 29 },
  { id: 4122, name: "นายูง", nameEn: "Na Yung", provinceId: 29 },
  { id: 4123, name: "พิบูลย์รักษ์", nameEn: "Phibun Rak", provinceId: 29 },
  { id: 4124, name: "กู่แก้ว", nameEn: "Ku Kaeo", provinceId: 29 },
  {
    id: 4125,
    name: "ประจักษ์ศิลปาคม",
    nameEn: "Prachaksinlapakhom",
    provinceId: 29,
  },
  { id: 4201, name: "เมืองเลย", nameEn: "Mueang Loei", provinceId: 30 },
  { id: 4202, name: "นาด้วง", nameEn: "Na Duang", provinceId: 30 },
  { id: 4203, name: "เชียงคาน", nameEn: "Chiang Khan", provinceId: 30 },
  { id: 4204, name: "ปากชม", nameEn: "Pak Chom", provinceId: 30 },
  { id: 4205, name: "ด่านซ้าย", nameEn: "Dan Sai", provinceId: 30 },
  { id: 4206, name: "นาแห้ว", nameEn: "Na Haeo", provinceId: 30 },
  { id: 4207, name: "ภูเรือ", nameEn: "Phu Ruea", provinceId: 30 },
  { id: 4208, name: "ท่าลี่", nameEn: "Tha Li", provinceId: 30 },
  { id: 4209, name: "วังสะพุง", nameEn: "Wang Saphung", provinceId: 30 },
  { id: 4210, name: "ภูกระดึง", nameEn: "Phu Kradueng", provinceId: 30 },
  { id: 4211, name: "ภูหลวง", nameEn: "Phu Luang", provinceId: 30 },
  { id: 4212, name: "ผาขาว", nameEn: "Pha Khao", provinceId: 30 },
  { id: 4213, name: "เอราวัณ", nameEn: "Erawan", provinceId: 30 },
  { id: 4214, name: "หนองหิน", nameEn: "Nong Hin", provinceId: 30 },
  {
    id: 4301,
    name: "เมืองหนองคาย",
    nameEn: "Mueang Nong Khai",
    provinceId: 31,
  },
  { id: 4302, name: "ท่าบ่อ", nameEn: "Tha Bo", provinceId: 31 },
  { id: 4305, name: "โพนพิสัย", nameEn: "Phon Phisai", provinceId: 31 },
  { id: 4307, name: "ศรีเชียงใหม่", nameEn: "Si Chiang Mai", provinceId: 31 },
  { id: 4308, name: "สังคม", nameEn: "Sangkhom", provinceId: 31 },
  { id: 4314, name: "สระใคร", nameEn: "Sakhrai", provinceId: 31 },
  { id: 4315, name: "เฝ้าไร่", nameEn: "Fao Rai", provinceId: 31 },
  { id: 4316, name: "รัตนวาปี", nameEn: "Rattanawapi", provinceId: 31 },
  { id: 4317, name: "โพธิ์ตาก", nameEn: "Pho Tak", provinceId: 31 },
  {
    id: 4401,
    name: "เมืองมหาสารคาม",
    nameEn: "Mueang Maha Sarakham",
    provinceId: 32,
  },
  { id: 4402, name: "แกดำ", nameEn: "Kae Dam", provinceId: 32 },
  { id: 4403, name: "โกสุมพิสัย", nameEn: "Kosum Phisai", provinceId: 32 },
  { id: 4404, name: "กันทรวิชัย", nameEn: "Kantharawichai", provinceId: 32 },
  { id: 4405, name: "เชียงยืน", nameEn: "Chiang Yuen", provinceId: 32 },
  { id: 4406, name: "บรบือ", nameEn: "Borabue", provinceId: 32 },
  { id: 4407, name: "นาเชือก", nameEn: "Na Chueak", provinceId: 32 },
  {
    id: 4408,
    name: "พยัคฆภูมิพิสัย",
    nameEn: "Phayakkhaphum Phisai",
    provinceId: 32,
  },
  { id: 4409, name: "วาปีปทุม", nameEn: "Wapi Pathum", provinceId: 32 },
  { id: 4410, name: "นาดูน", nameEn: "Na Dun", provinceId: 32 },
  { id: 4411, name: "ยางสีสุราช", nameEn: "Yang Sisurat", provinceId: 32 },
  { id: 4412, name: "กุดรัง", nameEn: "Kut Rang", provinceId: 32 },
  { id: 4413, name: "ชื่นชม", nameEn: "Chuen Chom", provinceId: 32 },
  { id: 4501, name: "เมืองร้อยเอ็ด", nameEn: "Mueang Roi Et", provinceId: 33 },
  { id: 4502, name: "เกษตรวิสัย", nameEn: "Kaset Wisai", provinceId: 33 },
  { id: 4503, name: "ปทุมรัตต์", nameEn: "Pathum Rat", provinceId: 33 },
  {
    id: 4504,
    name: "จตุรพักตรพิมาน",
    nameEn: "Chaturaphak Phiman",
    provinceId: 33,
  },
  { id: 4505, name: "ธวัชบุรี", nameEn: "Thawat Buri", provinceId: 33 },
  { id: 4506, name: "พนมไพร", nameEn: "Phanom Phrai", provinceId: 33 },
  { id: 4507, name: "โพนทอง", nameEn: "Phon Thong", provinceId: 33 },
  { id: 4508, name: "โพธิ์ชัย", nameEn: "Pho Chai", provinceId: 33 },
  { id: 4509, name: "หนองพอก", nameEn: "Nong Phok", provinceId: 33 },
  { id: 4510, name: "เสลภูมิ", nameEn: "Selaphum", provinceId: 33 },
  { id: 4511, name: "สุวรรณภูมิ", nameEn: "Suwannaphum", provinceId: 33 },
  { id: 4512, name: "เมืองสรวง", nameEn: "Mueang Suang", provinceId: 33 },
  { id: 4513, name: "โพนทราย", nameEn: "Phon Sai", provinceId: 33 },
  { id: 4514, name: "อาจสามารถ", nameEn: "At Samat", provinceId: 33 },
  { id: 4515, name: "เมยวดี", nameEn: "Moei Wadi", provinceId: 33 },
  { id: 4516, name: "ศรีสมเด็จ", nameEn: "Si Somdet", provinceId: 33 },
  { id: 4517, name: "จังหาร", nameEn: "Changhan", provinceId: 33 },
  { id: 4518, name: "เชียงขวัญ", nameEn: "Chiang Khwan", provinceId: 33 },
  { id: 4519, name: "หนองฮี", nameEn: "Nong Hi", provinceId: 33 },
  { id: 4520, name: "ทุ่งเขาหลวง", nameEn: "Thung Khao Luang", provinceId: 33 },
  {
    id: 4601,
    name: "เมืองกาฬสินธุ์",
    nameEn: "Mueang Kalasin",
    provinceId: 34,
  },
  { id: 4602, name: "นามน", nameEn: "Na Mon", provinceId: 34 },
  { id: 4603, name: "กมลาไสย", nameEn: "Kamalasai", provinceId: 34 },
  { id: 4604, name: "ร่องคำ", nameEn: "Rong Kham", provinceId: 34 },
  { id: 4605, name: "กุฉินารายณ์", nameEn: "Kuchinarai", provinceId: 34 },
  { id: 4606, name: "เขาวง", nameEn: "Khao Wong", provinceId: 34 },
  { id: 4607, name: "ยางตลาด", nameEn: "Yang Talat", provinceId: 34 },
  { id: 4608, name: "ห้วยเม็ก", nameEn: "Huai Mek", provinceId: 34 },
  { id: 4609, name: "สหัสขันธ์", nameEn: "Sahatsakhan", provinceId: 34 },
  { id: 4610, name: "คำม่วง", nameEn: "Kham Muang", provinceId: 34 },
  { id: 4611, name: "ท่าคันโท", nameEn: "Tha Khantho", provinceId: 34 },
  { id: 4612, name: "หนองกุงศรี", nameEn: "Nong Kung Si", provinceId: 34 },
  { id: 4613, name: "สมเด็จ", nameEn: "Somdet", provinceId: 34 },
  { id: 4614, name: "ห้วยผึ้ง", nameEn: "Huai Phueng", provinceId: 34 },
  { id: 4615, name: "สามชัย", nameEn: "Sam Chai", provinceId: 34 },
  { id: 4616, name: "นาคู", nameEn: "Na Khu", provinceId: 34 },
  { id: 4617, name: "ดอนจาน", nameEn: "Don Chan", provinceId: 34 },
  { id: 4618, name: "ฆ้องชัย", nameEn: "Khong Chai", provinceId: 34 },
  {
    id: 4701,
    name: "เมืองสกลนคร",
    nameEn: "Mueang Sakon Nakhon",
    provinceId: 35,
  },
  { id: 4702, name: "กุสุมาลย์", nameEn: "Kusuman", provinceId: 35 },
  { id: 4703, name: "กุดบาก", nameEn: "Kut Bak", provinceId: 35 },
  { id: 4704, name: "พรรณานิคม", nameEn: "Phanna Nikhom", provinceId: 35 },
  { id: 4705, name: "พังโคน", nameEn: "Phang Khon", provinceId: 35 },
  { id: 4706, name: "วาริชภูมิ", nameEn: "Waritchaphum", provinceId: 35 },
  { id: 4707, name: "นิคมน้ำอูน", nameEn: "Nikhom Nam Un", provinceId: 35 },
  { id: 4708, name: "วานรนิวาส", nameEn: "Wanon Niwat", provinceId: 35 },
  { id: 4709, name: "คำตากล้า", nameEn: "Kham Ta Kla", provinceId: 35 },
  { id: 4710, name: "บ้านม่วง", nameEn: "Ban Muang", provinceId: 35 },
  { id: 4711, name: "อากาศอำนวย", nameEn: "Akat Amnuai", provinceId: 35 },
  { id: 4712, name: "สว่างแดนดิน", nameEn: "Sawang Daen Din", provinceId: 35 },
  { id: 4713, name: "ส่องดาว", nameEn: "Song Dao", provinceId: 35 },
  { id: 4714, name: "เต่างอย", nameEn: "Tao Ngoi", provinceId: 35 },
  { id: 4715, name: "โคกศรีสุพรรณ", nameEn: "Khok Si Suphan", provinceId: 35 },
  { id: 4716, name: "เจริญศิลป์", nameEn: "Charoen Sin", provinceId: 35 },
  { id: 4717, name: "โพนนาแก้ว", nameEn: "Phon Na Kaeo", provinceId: 35 },
  { id: 4718, name: "ภูพาน", nameEn: "Phu Phan", provinceId: 35 },
  {
    id: 4801,
    name: "เมืองนครพนม",
    nameEn: "Mueang Nakhon Phanom",
    provinceId: 36,
  },
  { id: 4802, name: "ปลาปาก", nameEn: "Pla Pak", provinceId: 36 },
  { id: 4803, name: "ท่าอุเทน", nameEn: "Tha Uthen", provinceId: 36 },
  { id: 4804, name: "บ้านแพง", nameEn: "Ban Phaeng", provinceId: 36 },
  { id: 4805, name: "ธาตุพนม", nameEn: "That Phanom", provinceId: 36 },
  { id: 4806, name: "เรณูนคร", nameEn: "Renu Nakhon", provinceId: 36 },
  { id: 4807, name: "นาแก", nameEn: "Na Kae", provinceId: 36 },
  { id: 4808, name: "ศรีสงคราม", nameEn: "Si Songkhram", provinceId: 36 },
  { id: 4809, name: "นาหว้า", nameEn: "Na Wa", provinceId: 36 },
  { id: 4810, name: "โพนสวรรค์", nameEn: "Phon Sawan", provinceId: 36 },
  { id: 4811, name: "นาทม", nameEn: "Na Thom", provinceId: 36 },
  { id: 4812, name: "วังยาง", nameEn: "Wang Yang", provinceId: 36 },
  {
    id: 4901,
    name: "เมืองมุกดาหาร",
    nameEn: "Mueang Mukdahan",
    provinceId: 37,
  },
  { id: 4902, name: "นิคมคำสร้อย", nameEn: "Nikhom Kham Soi", provinceId: 37 },
  { id: 4903, name: "ดอนตาล", nameEn: "Don Tan", provinceId: 37 },
  { id: 4904, name: "ดงหลวง", nameEn: "Dong Luang", provinceId: 37 },
  { id: 4905, name: "คำชะอี", nameEn: "Khamcha-i", provinceId: 37 },
  { id: 4906, name: "หว้านใหญ่", nameEn: "Wan Yai", provinceId: 37 },
  { id: 4907, name: "หนองสูง", nameEn: "Nong Sung", provinceId: 37 },
  {
    id: 5001,
    name: "เมืองเชียงใหม่",
    nameEn: "Mueang Chiang Mai",
    provinceId: 38,
  },
  { id: 5002, name: "จอมทอง", nameEn: "Chom Thong", provinceId: 38 },
  { id: 5003, name: "แม่แจ่ม", nameEn: "Mae Chaem", provinceId: 38 },
  { id: 5004, name: "เชียงดาว", nameEn: "Chiang Dao", provinceId: 38 },
  { id: 5005, name: "ดอยสะเก็ด", nameEn: "Doi Saket", provinceId: 38 },
  { id: 5006, name: "แม่แตง", nameEn: "Mae Taeng", provinceId: 38 },
  { id: 5007, name: "แม่ริม", nameEn: "Mae Rim", provinceId: 38 },
  { id: 5008, name: "สะเมิง", nameEn: "Samoeng", provinceId: 38 },
  { id: 5009, name: "ฝาง", nameEn: "Fang", provinceId: 38 },
  { id: 5010, name: "แม่อาย", nameEn: "Mae Ai", provinceId: 38 },
  { id: 5011, name: "พร้าว", nameEn: "Phrao", provinceId: 38 },
  { id: 5012, name: "สันป่าตอง", nameEn: "San Pa Tong", provinceId: 38 },
  { id: 5013, name: "สันกำแพง", nameEn: "San Kamphaeng", provinceId: 38 },
  { id: 5014, name: "สันทราย", nameEn: "San Sai", provinceId: 38 },
  { id: 5015, name: "หางดง", nameEn: "Hang Dong", provinceId: 38 },
  { id: 5016, name: "ฮอด", nameEn: "Hot", provinceId: 38 },
  { id: 5017, name: "ดอยเต่า", nameEn: "Doi Tao", provinceId: 38 },
  { id: 5018, name: "อมก๋อย", nameEn: "Omkoi", provinceId: 38 },
  { id: 5019, name: "สารภี", nameEn: "Saraphi", provinceId: 38 },
  { id: 5020, name: "เวียงแหง", nameEn: "Wiang Haeng", provinceId: 38 },
  { id: 5021, name: "ไชยปราการ", nameEn: "Chai Prakan", provinceId: 38 },
  { id: 5022, name: "แม่วาง", nameEn: "Mae Wang", provinceId: 38 },
  { id: 5023, name: "แม่ออน", nameEn: "Mae On", provinceId: 38 },
  { id: 5024, name: "ดอยหล่อ", nameEn: "Doi Lo", provinceId: 38 },
  { id: 5025, name: "กัลยาณิวัฒนา", nameEn: "Galyani Vadhana", provinceId: 38 },
  { id: 5101, name: "เมืองลำพูน", nameEn: "Mueang Lamphun", provinceId: 39 },
  { id: 5102, name: "แม่ทา", nameEn: "Mae Tha", provinceId: 39 },
  { id: 5103, name: "บ้านโฮ่ง", nameEn: "Ban Hong", provinceId: 39 },
  { id: 5104, name: "ลี้", nameEn: "Li", provinceId: 39 },
  { id: 5105, name: "ทุ่งหัวช้าง", nameEn: "Thung Hua Chang", provinceId: 39 },
  { id: 5106, name: "ป่าซาง", nameEn: "Pa Sang", provinceId: 39 },
  { id: 5107, name: "บ้านธิ", nameEn: "Ban Thi", provinceId: 39 },
  {
    id: 5108,
    name: "เวียงหนองล่อง",
    nameEn: "Wiang Nong Long",
    provinceId: 39,
  },
  { id: 5201, name: "เมืองลำปาง", nameEn: "Mueang Lampang", provinceId: 40 },
  { id: 5202, name: "แม่เมาะ", nameEn: "Mae Mo", provinceId: 40 },
  { id: 5203, name: "เกาะคา", nameEn: "Ko Kha", provinceId: 40 },
  { id: 5204, name: "เสริมงาม", nameEn: "Soem Ngam", provinceId: 40 },
  { id: 5205, name: "งาว", nameEn: "Ngao", provinceId: 40 },
  { id: 5206, name: "แจ้ห่ม", nameEn: "Chae Hom", provinceId: 40 },
  { id: 5207, name: "วังเหนือ", nameEn: "Wang Nuea", provinceId: 40 },
  { id: 5208, name: "เถิน", nameEn: "Thoen", provinceId: 40 },
  { id: 5209, name: "แม่พริก", nameEn: "Mae Phrik", provinceId: 40 },
  { id: 5210, name: "แม่ทะ", nameEn: "Mae Tha", provinceId: 40 },
  { id: 5211, name: "สบปราบ", nameEn: "Sop Prap", provinceId: 40 },
  { id: 5212, name: "ห้างฉัตร", nameEn: "Hang Chat", provinceId: 40 },
  { id: 5213, name: "เมืองปาน", nameEn: "Mueang Pan", provinceId: 40 },
  {
    id: 5301,
    name: "เมืองอุตรดิตถ์",
    nameEn: "Mueang Uttaradit",
    provinceId: 41,
  },
  { id: 5302, name: "ตรอน", nameEn: "Tron", provinceId: 41 },
  { id: 5303, name: "ท่าปลา", nameEn: "Tha Pla", provinceId: 41 },
  { id: 5304, name: "น้ำปาด", nameEn: "Nam Pat", provinceId: 41 },
  { id: 5305, name: "ฟากท่า", nameEn: "Fak Tha", provinceId: 41 },
  { id: 5306, name: "บ้านโคก", nameEn: "Ban Khok", provinceId: 41 },
  { id: 5307, name: "พิชัย", nameEn: "Phichai", provinceId: 41 },
  { id: 5308, name: "ลับแล", nameEn: "Laplae", provinceId: 41 },
  { id: 5309, name: "ทองแสนขัน", nameEn: "Thong Saen Khan", provinceId: 41 },
  { id: 5401, name: "เมืองแพร่", nameEn: "Mueang Phrae", provinceId: 42 },
  { id: 5402, name: "ร้องกวาง", nameEn: "Rong Kwang", provinceId: 42 },
  { id: 5403, name: "ลอง", nameEn: "Long", provinceId: 42 },
  { id: 5404, name: "สูงเม่น", nameEn: "Sung Men", provinceId: 42 },
  { id: 5405, name: "เด่นชัย", nameEn: "Den Chai", provinceId: 42 },
  { id: 5406, name: "สอง", nameEn: "Song", provinceId: 42 },
  { id: 5407, name: "วังชิ้น", nameEn: "Wang Chin", provinceId: 42 },
  { id: 5408, name: "หนองม่วงไข่", nameEn: "Nong Muang Khai", provinceId: 42 },
  { id: 5501, name: "เมืองน่าน", nameEn: "Mueang Nan", provinceId: 43 },
  { id: 5502, name: "แม่จริม", nameEn: "Mae Charim", provinceId: 43 },
  { id: 5503, name: "บ้านหลวง", nameEn: "Ban Luang", provinceId: 43 },
  { id: 5504, name: "นาน้อย", nameEn: "Na Noi", provinceId: 43 },
  { id: 5505, name: "ปัว", nameEn: "Pua", provinceId: 43 },
  { id: 5506, name: "ท่าวังผา", nameEn: "Tha Wang Pha", provinceId: 43 },
  { id: 5507, name: "เวียงสา", nameEn: "Wiang Sa", provinceId: 43 },
  { id: 5508, name: "ทุ่งช้าง", nameEn: "Thung Chang", provinceId: 43 },
  { id: 5509, name: "เชียงกลาง", nameEn: "Chiang Klang", provinceId: 43 },
  { id: 5510, name: "นาหมื่น", nameEn: "Na Muen", provinceId: 43 },
  { id: 5511, name: "สันติสุข", nameEn: "Santi Suk", provinceId: 43 },
  { id: 5512, name: "บ่อเกลือ", nameEn: "Bo Kluea", provinceId: 43 },
  { id: 5513, name: "สองแคว", nameEn: "Song Khwae", provinceId: 43 },
  { id: 5514, name: "ภูเพียง", nameEn: "Phu Phiang", provinceId: 43 },
  {
    id: 5515,
    name: "เฉลิมพระเกียรติ",
    nameEn: "Chaloem Phra Kiat",
    provinceId: 43,
  },
  { id: 5601, name: "เมืองพะเยา", nameEn: "Mueang Phayao", provinceId: 44 },
  { id: 5602, name: "จุน", nameEn: "Chun", provinceId: 44 },
  { id: 5603, name: "เชียงคำ", nameEn: "Chiang Kham", provinceId: 44 },
  { id: 5604, name: "เชียงม่วน", nameEn: "Chiang Muan", provinceId: 44 },
  { id: 5605, name: "ดอกคำใต้", nameEn: "Dok Khamtai", provinceId: 44 },
  { id: 5606, name: "ปง", nameEn: "Pong", provinceId: 44 },
  { id: 5607, name: "แม่ใจ", nameEn: "Mae Chai", provinceId: 44 },
  { id: 5608, name: "ภูซาง", nameEn: "Phu Sang", provinceId: 44 },
  { id: 5609, name: "ภูกามยาว", nameEn: "Phu Kamyao", provinceId: 44 },
  {
    id: 5701,
    name: "เมืองเชียงราย",
    nameEn: "Mueang Chiang Rai",
    provinceId: 45,
  },
  { id: 5702, name: "เวียงชัย", nameEn: "Wiang Chai", provinceId: 45 },
  { id: 5703, name: "เชียงของ", nameEn: "Chiang Khong", provinceId: 45 },
  { id: 5704, name: "เทิง", nameEn: "Thoeng", provinceId: 45 },
  { id: 5705, name: "พาน", nameEn: "Phan", provinceId: 45 },
  { id: 5706, name: "ป่าแดด", nameEn: "Pa Daet", provinceId: 45 },
  { id: 5707, name: "แม่จัน", nameEn: "Mae Chan", provinceId: 45 },
  { id: 5708, name: "เชียงแสน", nameEn: "Chiang Saen", provinceId: 45 },
  { id: 5709, name: "แม่สาย", nameEn: "Mae Sai", provinceId: 45 },
  { id: 5710, name: "แม่สรวย", nameEn: "Mae Suai", provinceId: 45 },
  { id: 5711, name: "เวียงป่าเป้า", nameEn: "Wiang Pa Pao", provinceId: 45 },
  { id: 5712, name: "พญาเม็งราย", nameEn: "Phaya Mengrai", provinceId: 45 },
  { id: 5713, name: "เวียงแก่น", nameEn: "Wiang Kaen", provinceId: 45 },
  { id: 5714, name: "ขุนตาล", nameEn: "Khun Tan", provinceId: 45 },
  { id: 5715, name: "แม่ฟ้าหลวง", nameEn: "Mae Fa Luang", provinceId: 45 },
  { id: 5716, name: "แม่ลาว", nameEn: "Mae Lao", provinceId: 45 },
  {
    id: 5717,
    name: "เวียงเชียงรุ้ง",
    nameEn: "Wiang Chiang Rung",
    provinceId: 45,
  },
  { id: 5718, name: "ดอยหลวง", nameEn: "Doi Luang", provinceId: 45 },
  {
    id: 5801,
    name: "เมืองแม่ฮ่องสอน",
    nameEn: "Mueang Mae Hong Son",
    provinceId: 46,
  },
  { id: 5802, name: "ขุนยวม", nameEn: "Khun Yuam", provinceId: 46 },
  { id: 5803, name: "ปาย", nameEn: "Pai", provinceId: 46 },
  { id: 5804, name: "แม่สะเรียง", nameEn: "Mae Sariang", provinceId: 46 },
  { id: 5805, name: "แม่ลาน้อย", nameEn: "Mae La Noi", provinceId: 46 },
  { id: 5806, name: "สบเมย", nameEn: "Sop Moei", provinceId: 46 },
  { id: 5807, name: "ปางมะผ้า", nameEn: "Pang Mapha", provinceId: 46 },
  {
    id: 6001,
    name: "เมืองนครสวรรค์",
    nameEn: "Mueang Nakhon Sawan",
    provinceId: 47,
  },
  { id: 6002, name: "โกรกพระ", nameEn: "Krok Phra", provinceId: 47 },
  { id: 6003, name: "ชุมแสง", nameEn: "Chum Saeng", provinceId: 47 },
  { id: 6004, name: "หนองบัว", nameEn: "Nong Bua", provinceId: 47 },
  { id: 6005, name: "บรรพตพิสัย", nameEn: "Banphot Phisai", provinceId: 47 },
  { id: 6006, name: "เก้าเลี้ยว", nameEn: "Kao Liao", provinceId: 47 },
  { id: 6007, name: "ตาคลี", nameEn: "Takhli", provinceId: 47 },
  { id: 6008, name: "ท่าตะโก", nameEn: "Takhli", provinceId: 47 },
  { id: 6009, name: "ไพศาลี", nameEn: "Phaisali", provinceId: 47 },
  { id: 6010, name: "พยุหะคีรี", nameEn: "Phayuha Khiri", provinceId: 47 },
  { id: 6011, name: "ลาดยาว", nameEn: "Phayuha Khiri", provinceId: 47 },
  { id: 6012, name: "ตากฟ้า", nameEn: "Tak Fa", provinceId: 47 },
  { id: 6013, name: "แม่วงก์", nameEn: "Mae Wong", provinceId: 47 },
  { id: 6014, name: "แม่เปิน", nameEn: "Mae Poen", provinceId: 47 },
  { id: 6015, name: "ชุมตาบง", nameEn: "Chum Ta Bong", provinceId: 47 },
  {
    id: 6101,
    name: "เมืองอุทัยธานี",
    nameEn: "Mueang Uthai Thani",
    provinceId: 48,
  },
  { id: 6102, name: "ทัพทัน", nameEn: "Thap Than", provinceId: 48 },
  { id: 6103, name: "สว่างอารมณ์", nameEn: "Sawang Arom", provinceId: 48 },
  { id: 6104, name: "หนองฉาง", nameEn: "Nong Chang", provinceId: 48 },
  { id: 6105, name: "หนองขาหย่าง", nameEn: "Nong Khayang", provinceId: 48 },
  { id: 6106, name: "บ้านไร่", nameEn: "Ban Rai", provinceId: 48 },
  { id: 6107, name: "ลานสัก", nameEn: "Lan Sak", provinceId: 48 },
  { id: 6108, name: "ห้วยคต", nameEn: "Huai Khot", provinceId: 48 },
  {
    id: 6201,
    name: "เมืองกำแพงเพชร",
    nameEn: "Mueang Kamphaeng Phet",
    provinceId: 49,
  },
  { id: 6202, name: "ไทรงาม", nameEn: "Sai Ngam", provinceId: 49 },
  { id: 6203, name: "คลองลาน", nameEn: "Khlong Lan", provinceId: 49 },
  {
    id: 6204,
    name: "ขาณุวรลักษบุรี",
    nameEn: "Khanu Woralaksaburi",
    provinceId: 49,
  },
  { id: 6205, name: "คลองขลุง", nameEn: "Khlong Khlung", provinceId: 49 },
  { id: 6206, name: "พรานกระต่าย", nameEn: "Phran Kratai", provinceId: 49 },
  { id: 6207, name: "ลานกระบือ", nameEn: "Lan Krabue", provinceId: 49 },
  {
    id: 6208,
    name: "ทรายทองวัฒนา",
    nameEn: "Sai Thong Watthana",
    provinceId: 49,
  },
  { id: 6209, name: "ปางศิลาทอง", nameEn: "Pang Sila Thong", provinceId: 49 },
  { id: 6210, name: "บึงสามัคคี", nameEn: "Bueng Samakkhi", provinceId: 49 },
  { id: 6211, name: "โกสัมพีนคร", nameEn: "Kosamphi Nakhon", provinceId: 49 },
  { id: 6301, name: "เมืองตาก", nameEn: "Mueang Tak", provinceId: 50 },
  { id: 6302, name: "บ้านตาก", nameEn: "Ban Tak", provinceId: 50 },
  { id: 6303, name: "สามเงา", nameEn: "Sam Ngao", provinceId: 50 },
  { id: 6304, name: "แม่ระมาด", nameEn: "Mae Ramat", provinceId: 50 },
  { id: 6305, name: "ท่าสองยาง", nameEn: "Tha Song Yang", provinceId: 50 },
  { id: 6306, name: "แม่สอด", nameEn: "Mae Sot", provinceId: 50 },
  { id: 6307, name: "พบพระ", nameEn: "Phop Phra", provinceId: 50 },
  { id: 6308, name: "อุ้มผาง", nameEn: "Umphang", provinceId: 50 },
  { id: 6309, name: "วังเจ้า", nameEn: "Wang Chao", provinceId: 50 },
  {
    id: 6401,
    name: "เมืองสุโขทัย",
    nameEn: "Mueang Sukhothai",
    provinceId: 51,
  },
  {
    id: 6402,
    name: "บ้านด่านลานหอย",
    nameEn: "Ban Dan Lan Hoi",
    provinceId: 51,
  },
  { id: 6403, name: "คีรีมาศ", nameEn: "Khiri Mat", provinceId: 51 },
  { id: 6404, name: "กงไกรลาศ", nameEn: "Kong Krailat", provinceId: 51 },
  { id: 6405, name: "ศรีสัชนาลัย", nameEn: "Si Satchanalai", provinceId: 51 },
  { id: 6406, name: "ศรีสำโรง", nameEn: "Si Samrong", provinceId: 51 },
  { id: 6407, name: "สวรรคโลก", nameEn: "Sawankhalok", provinceId: 51 },
  { id: 6408, name: "ศรีนคร", nameEn: "Si Nakhon", provinceId: 51 },
  { id: 6409, name: "ทุ่งเสลี่ยม", nameEn: "Thung Saliam", provinceId: 51 },
  {
    id: 6501,
    name: "เมืองพิษณุโลก",
    nameEn: "Mueang Phitsanulok",
    provinceId: 52,
  },
  { id: 6502, name: "นครไทย", nameEn: "Nakhon Thai", provinceId: 52 },
  { id: 6503, name: "ชาติตระการ", nameEn: "Chat Trakan", provinceId: 52 },
  { id: 6504, name: "บางระกำ", nameEn: "Bang Rakam", provinceId: 52 },
  { id: 6505, name: "บางกระทุ่ม", nameEn: "Bang Krathum", provinceId: 52 },
  { id: 6506, name: "พรหมพิราม", nameEn: "Phrom Phiram", provinceId: 52 },
  { id: 6507, name: "วัดโบสถ์", nameEn: "Wat Bot", provinceId: 52 },
  { id: 6508, name: "วังทอง", nameEn: "Wang Thong", provinceId: 52 },
  { id: 6509, name: "เนินมะปราง", nameEn: "Noen Maprang", provinceId: 52 },
  { id: 6601, name: "เมืองพิจิตร", nameEn: "Mueang Phichit", provinceId: 53 },
  { id: 6602, name: "วังทรายพูน", nameEn: "Wang Sai Phun", provinceId: 53 },
  {
    id: 6603,
    name: "โพธิ์ประทับช้าง",
    nameEn: "Pho Prathap Chang",
    provinceId: 53,
  },
  { id: 6604, name: "ตะพานหิน", nameEn: "Taphan Hin", provinceId: 53 },
  { id: 6605, name: "บางมูลนาก", nameEn: "Bang Mun Nak", provinceId: 53 },
  { id: 6606, name: "โพทะเล", nameEn: "Pho Thale", provinceId: 53 },
  { id: 6607, name: "สามง่าม", nameEn: "Sam Ngam", provinceId: 53 },
  { id: 6608, name: "ทับคล้อ", nameEn: "Tap Khlo", provinceId: 53 },
  { id: 6609, name: "สากเหล็ก", nameEn: "Sak Lek", provinceId: 53 },
  { id: 6610, name: "บึงนาราง", nameEn: "Bueng Na Rang", provinceId: 53 },
  { id: 6611, name: "ดงเจริญ", nameEn: "Dong Charoen", provinceId: 53 },
  { id: 6612, name: "วชิรบารมี", nameEn: "Wachirabarami", provinceId: 53 },
  {
    id: 6701,
    name: "เมืองเพชรบูรณ์",
    nameEn: "Mueang Phetchabun",
    provinceId: 54,
  },
  { id: 6702, name: "ชนแดน", nameEn: "Chon Daen", provinceId: 54 },
  { id: 6703, name: "หล่มสัก", nameEn: "Lom Sak", provinceId: 54 },
  { id: 6704, name: "หล่มเก่า", nameEn: "Lom Kao", provinceId: 54 },
  { id: 6705, name: "วิเชียรบุรี", nameEn: "Wichian Buri", provinceId: 54 },
  { id: 6706, name: "ศรีเทพ", nameEn: "Si Thep", provinceId: 54 },
  { id: 6707, name: "หนองไผ่", nameEn: "Nong Phai", provinceId: 54 },
  { id: 6708, name: "บึงสามพัน", nameEn: "Bueng Sam Phan", provinceId: 54 },
  { id: 6709, name: "น้ำหนาว", nameEn: "Nam Nao", provinceId: 54 },
  { id: 6710, name: "วังโป่ง", nameEn: "Wang Pong", provinceId: 54 },
  { id: 6711, name: "เขาค้อ", nameEn: "Khao Kho", provinceId: 54 },
  {
    id: 7001,
    name: "เมืองราชบุรี",
    nameEn: "Mueang Ratchaburi",
    provinceId: 55,
  },
  { id: 7002, name: "จอมบึง", nameEn: "Chom Bueng", provinceId: 55 },
  { id: 7003, name: "สวนผึ้ง", nameEn: "Suan Phueng", provinceId: 55 },
  { id: 7004, name: "ดำเนินสะดวก", nameEn: "Damnoen Saduak", provinceId: 55 },
  { id: 7005, name: "บ้านโป่ง", nameEn: "Ban Pong", provinceId: 55 },
  { id: 7006, name: "บางแพ", nameEn: "Bang Phae", provinceId: 55 },
  { id: 7007, name: "โพธาราม", nameEn: "Photharam", provinceId: 55 },
  { id: 7008, name: "ปากท่อ", nameEn: "Pak Tho", provinceId: 55 },
  { id: 7009, name: "วัดเพลง", nameEn: "Wat Phleng", provinceId: 55 },
  { id: 7010, name: "บ้านคา", nameEn: "Ban Kha", provinceId: 55 },
  {
    id: 7074,
    name: "ท้องถิ่นเทศบาลตำบลบ้านฆ้อง",
    nameEn: "Tet Saban Ban Kong",
    provinceId: 55,
  },
  {
    id: 7101,
    name: "เมืองกาญจนบุรี",
    nameEn: "Mueang Kanchanaburi",
    provinceId: 56,
  },
  { id: 7102, name: "ไทรโยค", nameEn: "Sai Yok", provinceId: 56 },
  { id: 7103, name: "บ่อพลอย", nameEn: "Bo Phloi", provinceId: 56 },
  { id: 7104, name: "ศรีสวัสดิ์", nameEn: "Si Sawat", provinceId: 56 },
  { id: 7105, name: "ท่ามะกา", nameEn: "Tha Maka", provinceId: 56 },
  { id: 7106, name: "ท่าม่วง", nameEn: "Tha Muang", provinceId: 56 },
  { id: 7107, name: "ทองผาภูมิ", nameEn: "Pha Phum", provinceId: 56 },
  { id: 7108, name: "สังขละบุรี", nameEn: "Sangkhla Buri", provinceId: 56 },
  { id: 7109, name: "พนมทวน", nameEn: "Phanom Thuan", provinceId: 56 },
  { id: 7110, name: "เลาขวัญ", nameEn: "Lao Khwan", provinceId: 56 },
  {
    id: 7111,
    name: "ด่านมะขามเตี้ย",
    nameEn: "Dan Makham Tia",
    provinceId: 56,
  },
  { id: 7112, name: "หนองปรือ", nameEn: "Nong Prue", provinceId: 56 },
  { id: 7113, name: "ห้วยกระเจา", nameEn: "Huai Krachao", provinceId: 56 },
  {
    id: 7201,
    name: "เมืองสุพรรณบุรี",
    nameEn: "Mueang Suphan Buri",
    provinceId: 57,
  },
  {
    id: 7202,
    name: "เดิมบางนางบวช",
    nameEn: "Doem Bang Nang Buat",
    provinceId: 57,
  },
  { id: 7203, name: "ด่านช้าง", nameEn: "Dan Chang", provinceId: 57 },
  { id: 7204, name: "บางปลาม้า", nameEn: "Bang Pla Ma", provinceId: 57 },
  { id: 7205, name: "ศรีประจันต์", nameEn: "Si Prachan", provinceId: 57 },
  { id: 7206, name: "ดอนเจดีย์", nameEn: "Don Chedi", provinceId: 57 },
  { id: 7207, name: "สองพี่น้อง", nameEn: "Song Phi Nong", provinceId: 57 },
  { id: 7208, name: "สามชุก", nameEn: "Sam Chuk", provinceId: 57 },
  { id: 7209, name: "อู่ทอง", nameEn: "U Thong", provinceId: 57 },
  { id: 7210, name: "หนองหญ้าไซ", nameEn: "Nong Ya Sai", provinceId: 57 },
  {
    id: 7301,
    name: "เมืองนครปฐม",
    nameEn: "Mueang Nakhon Pathom",
    provinceId: 58,
  },
  { id: 7302, name: "กำแพงแสน", nameEn: "Kamphaeng Saen", provinceId: 58 },
  { id: 7303, name: "นครชัยศรี", nameEn: "Nakhon Chai Si", provinceId: 58 },
  { id: 7304, name: "ดอนตูม", nameEn: "Don Tum", provinceId: 58 },
  { id: 7305, name: "บางเลน", nameEn: "Bang Len", provinceId: 58 },
  { id: 7306, name: "สามพราน", nameEn: "Sam Phran", provinceId: 58 },
  { id: 7307, name: "พุทธมณฑล", nameEn: "Phutthamonthon", provinceId: 58 },
  {
    id: 7401,
    name: "เมืองสมุทรสาคร",
    nameEn: "Mueang Samut Sakhon",
    provinceId: 59,
  },
  { id: 7402, name: "กระทุ่มแบน", nameEn: "Krathum Baen", provinceId: 59 },
  { id: 7403, name: "บ้านแพ้ว", nameEn: "Ban Phaeo", provinceId: 59 },
  {
    id: 7501,
    name: "เมืองสมุทรสงคราม",
    nameEn: "Mueang Samut Songkhram",
    provinceId: 60,
  },
  { id: 7502, name: "บางคนที", nameEn: "Bang Khonthi", provinceId: 60 },
  { id: 7503, name: "อัมพวา", nameEn: "Amphawa", provinceId: 60 },
  {
    id: 7601,
    name: "เมืองเพชรบุรี",
    nameEn: "Mueang Phetchaburi",
    provinceId: 61,
  },
  { id: 7602, name: "เขาย้อย", nameEn: "Khao Yoi", provinceId: 61 },
  { id: 7603, name: "หนองหญ้าปล้อง", nameEn: "Nong Ya Plong", provinceId: 61 },
  { id: 7604, name: "ชะอำ", nameEn: "Cha-am", provinceId: 61 },
  { id: 7605, name: "ท่ายาง", nameEn: "Tha Yang", provinceId: 61 },
  { id: 7606, name: "บ้านลาด", nameEn: "Ban Lat", provinceId: 61 },
  { id: 7607, name: "บ้านแหลม", nameEn: "Ban Laem", provinceId: 61 },
  { id: 7608, name: "แก่งกระจาน", nameEn: "Kaeng Krachan", provinceId: 61 },
  {
    id: 7701,
    name: "เมืองประจวบคีรีขันธ์",
    nameEn: "Mueang Prachuap Khiri Khan",
    provinceId: 62,
  },
  { id: 7702, name: "กุยบุรี", nameEn: "Kui Buri", provinceId: 62 },
  { id: 7703, name: "ทับสะแก", nameEn: "Thap Sakae", provinceId: 62 },
  { id: 7704, name: "บางสะพาน", nameEn: "Bang Saphan", provinceId: 62 },
  { id: 7705, name: "บางสะพานน้อย", nameEn: "Bang Saphan Noi", provinceId: 62 },
  { id: 7706, name: "ปราณบุรี", nameEn: "Pran Buri", provinceId: 62 },
  { id: 7707, name: "หัวหิน", nameEn: "Hua Hin", provinceId: 62 },
  { id: 7708, name: "สามร้อยยอด", nameEn: "Sam Roi Yot", provinceId: 62 },
  {
    id: 8001,
    name: "เมืองนครศรีธรรมราช",
    nameEn: "Mueang Nakhon Si Thammarat",
    provinceId: 63,
  },
  { id: 8002, name: "พรหมคีรี", nameEn: "Phrom Khiri", provinceId: 63 },
  { id: 8003, name: "ลานสกา", nameEn: "Lan Saka", provinceId: 63 },
  { id: 8004, name: "ฉวาง", nameEn: "Chawang", provinceId: 63 },
  { id: 8005, name: "พิปูน", nameEn: "Phipun", provinceId: 63 },
  { id: 8006, name: "เชียรใหญ่", nameEn: "Chian Yai", provinceId: 63 },
  { id: 8007, name: "ชะอวด", nameEn: "Cha-uat", provinceId: 63 },
  { id: 8008, name: "ท่าศาลา", nameEn: "Tha Sala", provinceId: 63 },
  { id: 8009, name: "ทุ่งสง", nameEn: "Thung Song", provinceId: 63 },
  { id: 8010, name: "นาบอน", nameEn: "Na Bon", provinceId: 63 },
  { id: 8011, name: "ทุ่งใหญ่", nameEn: "Thung Yai", provinceId: 63 },
  { id: 8012, name: "ปากพนัง", nameEn: "Pak Phanang", provinceId: 63 },
  { id: 8013, name: "ร่อนพิบูลย์", nameEn: "Ron Phibun", provinceId: 63 },
  { id: 8014, name: "สิชล", nameEn: "Sichon", provinceId: 63 },
  { id: 8015, name: "ขนอม", nameEn: "Khanom", provinceId: 63 },
  { id: 8016, name: "หัวไทร", nameEn: "Hua Sai", provinceId: 63 },
  { id: 8017, name: "บางขัน", nameEn: "Bang Khan", provinceId: 63 },
  { id: 8018, name: "ถ้ำพรรณรา", nameEn: "Tham Phannara", provinceId: 63 },
  { id: 8019, name: "จุฬาภรณ์", nameEn: "Chulabhorn", provinceId: 63 },
  { id: 8020, name: "พระพรหม", nameEn: "Phra Phrom", provinceId: 63 },
  { id: 8021, name: "นบพิตำ", nameEn: "Nopphitam", provinceId: 63 },
  { id: 8022, name: "ช้างกลาง", nameEn: "Chang Klang", provinceId: 63 },
  {
    id: 8023,
    name: "เฉลิมพระเกียรติ",
    nameEn: "Chaloem Phra Kiat",
    provinceId: 63,
  },
  { id: 8101, name: "เมืองกระบี่", nameEn: "Mueang Krabi", provinceId: 64 },
  { id: 8102, name: "เขาพนม", nameEn: "Khao Phanom", provinceId: 64 },
  { id: 8103, name: "เกาะลันตา", nameEn: "Ko Lanta", provinceId: 64 },
  { id: 8104, name: "คลองท่อม", nameEn: "Khlong Thom", provinceId: 64 },
  { id: 8105, name: "อ่าวลึก", nameEn: "Ao Luek", provinceId: 64 },
  { id: 8106, name: "ปลายพระยา", nameEn: "Plai Phraya", provinceId: 64 },
  { id: 8107, name: "ลำทับ", nameEn: "Lam Thap", provinceId: 64 },
  { id: 8108, name: "เหนือคลอง", nameEn: "Nuea Khlong", provinceId: 64 },
  { id: 8201, name: "เมืองพังงา", nameEn: "Mueang Phang-nga", provinceId: 65 },
  { id: 8202, name: "เกาะยาว", nameEn: "Ko Yao", provinceId: 65 },
  { id: 8203, name: "กะปง", nameEn: "Kapong", provinceId: 65 },
  { id: 8204, name: "ตะกั่วทุ่ง", nameEn: "Takua Thung", provinceId: 65 },
  { id: 8205, name: "ตะกั่วป่า", nameEn: "Takua Pa", provinceId: 65 },
  { id: 8206, name: "คุระบุรี", nameEn: "Khura Buri", provinceId: 65 },
  { id: 8207, name: "ทับปุด", nameEn: "Thap Put", provinceId: 65 },
  { id: 8208, name: "ท้ายเหมือง", nameEn: "Thai Mueang", provinceId: 65 },
  { id: 8301, name: "เมืองภูเก็ต", nameEn: "Mueang Phuket", provinceId: 66 },
  { id: 8302, name: "กะทู้", nameEn: "Kathu", provinceId: 66 },
  { id: 8303, name: "ถลาง", nameEn: "Thalang", provinceId: 66 },
  {
    id: 8401,
    name: "เมืองสุราษฎร์ธานี",
    nameEn: "Mueang Surat Thani",
    provinceId: 67,
  },
  { id: 8402, name: "กาญจนดิษฐ์", nameEn: "Kanchanadit", provinceId: 67 },
  { id: 8403, name: "ดอนสัก", nameEn: "Don Sak", provinceId: 67 },
  { id: 8404, name: "เกาะสมุย", nameEn: "Ko Samui", provinceId: 67 },
  { id: 8405, name: "เกาะพะงัน", nameEn: "Ko Pha-ngan", provinceId: 67 },
  { id: 8406, name: "ไชยา", nameEn: "Chaiya", provinceId: 67 },
  { id: 8407, name: "ท่าชนะ", nameEn: "Tha Chana", provinceId: 67 },
  { id: 8408, name: "คีรีรัฐนิคม", nameEn: "Khiri Rat Nikhom", provinceId: 67 },
  { id: 8409, name: "บ้านตาขุน", nameEn: "Ban Ta Khun", provinceId: 67 },
  { id: 8410, name: "พนม", nameEn: "Phanom", provinceId: 67 },
  { id: 8411, name: "ท่าฉาง", nameEn: "Tha Chang", provinceId: 67 },
  { id: 8412, name: "บ้านนาสาร", nameEn: "Ban Na San", provinceId: 67 },
  { id: 8413, name: "บ้านนาเดิม", nameEn: "Ban Na Doem", provinceId: 67 },
  { id: 8414, name: "เคียนซา", nameEn: "Khian Sa", provinceId: 67 },
  { id: 8415, name: "เวียงสระ", nameEn: "Wiang Sa", provinceId: 67 },
  { id: 8416, name: "พระแสง", nameEn: "Phrasaeng", provinceId: 67 },
  { id: 8417, name: "พุนพิน", nameEn: "Phunphin", provinceId: 67 },
  { id: 8418, name: "ชัยบุรี", nameEn: "Chai Buri", provinceId: 67 },
  { id: 8419, name: "วิภาวดี", nameEn: "Vibhavadi", provinceId: 67 },
  { id: 8501, name: "เมืองระนอง", nameEn: "Mueang Ranong", provinceId: 68 },
  { id: 8502, name: "ละอุ่น", nameEn: "La-un", provinceId: 68 },
  { id: 8503, name: "กะเปอร์", nameEn: "Kapoe", provinceId: 68 },
  { id: 8504, name: "กระบุรี", nameEn: "Kra Buri", provinceId: 68 },
  { id: 8505, name: "สุขสำราญ", nameEn: "Suk Samran", provinceId: 68 },
  { id: 8601, name: "เมืองชุมพร", nameEn: "Mueang Chumphon", provinceId: 69 },
  { id: 8602, name: "ท่าแซะ", nameEn: "Tha Sae", provinceId: 69 },
  { id: 8603, name: "ปะทิว", nameEn: "Pathio", provinceId: 69 },
  { id: 8604, name: "หลังสวน", nameEn: "Lang Suan", provinceId: 69 },
  { id: 8605, name: "ละแม", nameEn: "Lamae", provinceId: 69 },
  { id: 8606, name: "พะโต๊ะ", nameEn: "Phato", provinceId: 69 },
  { id: 8607, name: "สวี", nameEn: "Sawi", provinceId: 69 },
  { id: 8608, name: "ทุ่งตะโก", nameEn: "Thung Tako", provinceId: 69 },
  { id: 9001, name: "เมืองสงขลา", nameEn: "Mueang Songkhla", provinceId: 70 },
  { id: 9002, name: "สทิงพระ", nameEn: "Sathing Phra", provinceId: 70 },
  { id: 9003, name: "จะนะ", nameEn: "Chana", provinceId: 70 },
  { id: 9004, name: "นาทวี", nameEn: "Na Thawi", provinceId: 70 },
  { id: 9005, name: "เทพา", nameEn: "Thepha", provinceId: 70 },
  { id: 9006, name: "สะบ้าย้อย", nameEn: "Saba Yoi", provinceId: 70 },
  { id: 9007, name: "ระโนด", nameEn: "Ranot", provinceId: 70 },
  { id: 9008, name: "กระแสสินธุ์", nameEn: "Krasae Sin", provinceId: 70 },
  { id: 9009, name: "รัตภูมิ", nameEn: "Rattaphum", provinceId: 70 },
  { id: 9010, name: "สะเดา", nameEn: "Sadao", provinceId: 70 },
  { id: 9011, name: "หาดใหญ่", nameEn: "Hat Yai", provinceId: 70 },
  { id: 9012, name: "นาหม่อม", nameEn: "Na Mom", provinceId: 70 },
  { id: 9013, name: "ควนเนียง", nameEn: "Khuan Niang", provinceId: 70 },
  { id: 9014, name: "บางกล่ำ", nameEn: "Bang Klam", provinceId: 70 },
  { id: 9015, name: "สิงหนคร", nameEn: "Singhanakhon", provinceId: 70 },
  { id: 9016, name: "คลองหอยโข่ง", nameEn: "Khlong Hoi Khong", provinceId: 70 },
  {
    id: 9077,
    name: "ท้องถิ่นเทศบาลตำบลสำนักขาม",
    nameEn: "Sum Nung Kam",
    provinceId: 70,
  },
  { id: 9101, name: "เมืองสตูล", nameEn: "Mueang Satun", provinceId: 71 },
  { id: 9102, name: "ควนโดน", nameEn: "Khuan Don", provinceId: 71 },
  { id: 9103, name: "ควนกาหลง", nameEn: "Khuan Kalong", provinceId: 71 },
  { id: 9104, name: "ท่าแพ", nameEn: "Tha Phae", provinceId: 71 },
  { id: 9105, name: "ละงู", nameEn: "La-ngu", provinceId: 71 },
  { id: 9106, name: "ทุ่งหว้า", nameEn: "Thung Wa", provinceId: 71 },
  { id: 9107, name: "มะนัง", nameEn: "Manang", provinceId: 71 },
  { id: 9201, name: "เมืองตรัง", nameEn: "Mueang Trang", provinceId: 72 },
  { id: 9202, name: "กันตัง", nameEn: "Kantang", provinceId: 72 },
  { id: 9203, name: "ย่านตาขาว", nameEn: "Yan Ta Khao", provinceId: 72 },
  { id: 9204, name: "ปะเหลียน", nameEn: "Palian", provinceId: 72 },
  { id: 9205, name: "สิเกา", nameEn: "Sikao", provinceId: 72 },
  { id: 9206, name: "ห้วยยอด", nameEn: "Huai Yot", provinceId: 72 },
  { id: 9207, name: "วังวิเศษ", nameEn: "Wang Wiset", provinceId: 72 },
  { id: 9208, name: "นาโยง", nameEn: "Na Yong", provinceId: 72 },
  { id: 9209, name: "รัษฎา", nameEn: "Ratsada", provinceId: 72 },
  { id: 9210, name: "หาดสำราญ", nameEn: "Hat Samran", provinceId: 72 },
  {
    id: 9301,
    name: "เมืองพัทลุง",
    nameEn: "Mueang Phatthalung",
    provinceId: 73,
  },
  { id: 9302, name: "กงหรา", nameEn: "Kong Ra", provinceId: 73 },
  { id: 9303, name: "เขาชัยสน", nameEn: "Khao Chaison", provinceId: 73 },
  { id: 9304, name: "ตะโหมด", nameEn: "Tamot", provinceId: 73 },
  { id: 9305, name: "ควนขนุน", nameEn: "Khuan Khanun", provinceId: 73 },
  { id: 9306, name: "ปากพะยูน", nameEn: "Pak Phayun", provinceId: 73 },
  { id: 9307, name: "ศรีบรรพต", nameEn: "Si Banphot", provinceId: 73 },
  { id: 9308, name: "ป่าบอน", nameEn: "Pa Bon", provinceId: 73 },
  { id: 9309, name: "บางแก้ว", nameEn: "Bang Kaeo", provinceId: 73 },
  { id: 9310, name: "ป่าพะยอม", nameEn: "Pa Phayom", provinceId: 73 },
  { id: 9311, name: "ศรีนครินทร์", nameEn: "Srinagarindra", provinceId: 73 },
  { id: 9401, name: "เมืองปัตตานี", nameEn: "Mueang Pattani", provinceId: 74 },
  { id: 9402, name: "โคกโพธิ์", nameEn: "Khok Pho", provinceId: 74 },
  { id: 9403, name: "หนองจิก", nameEn: "Nong Chik", provinceId: 74 },
  { id: 9404, name: "ปะนาเระ", nameEn: "Panare", provinceId: 74 },
  { id: 9405, name: "มายอ", nameEn: "Mayo", provinceId: 74 },
  { id: 9406, name: "ทุ่งยางแดง", nameEn: "Thung Yang Daeng", provinceId: 74 },
  { id: 9407, name: "สายบุรี", nameEn: "Sai Buri", provinceId: 74 },
  { id: 9408, name: "ไม้แก่น", nameEn: "Mai Kaen", provinceId: 74 },
  { id: 9409, name: "ยะหริ่ง", nameEn: "Yaring", provinceId: 74 },
  { id: 9410, name: "ยะรัง", nameEn: "Yarang", provinceId: 74 },
  { id: 9411, name: "กะพ้อ", nameEn: "Kapho", provinceId: 74 },
  { id: 9412, name: "แม่ลาน", nameEn: "Mae Lan", provinceId: 74 },
  { id: 9501, name: "เมืองยะลา", nameEn: "Mueang Yala", provinceId: 75 },
  { id: 9502, name: "เบตง", nameEn: "Betong", provinceId: 75 },
  { id: 9503, name: "บันนังสตา", nameEn: "Bannang Sata", provinceId: 75 },
  { id: 9504, name: "ธารโต", nameEn: "Than To", provinceId: 75 },
  { id: 9505, name: "ยะหา", nameEn: "Yaha", provinceId: 75 },
  { id: 9506, name: "รามัน", nameEn: "Raman", provinceId: 75 },
  { id: 9507, name: "กาบัง", nameEn: "Kabang", provinceId: 75 },
  { id: 9508, name: "กรงปินัง", nameEn: "Krong Pinang", provinceId: 75 },
  {
    id: 9601,
    name: "เมืองนราธิวาส",
    nameEn: "Mueang Narathiwat",
    provinceId: 76,
  },
  { id: 9602, name: "ตากใบ", nameEn: "Tak Bai", provinceId: 76 },
  { id: 9603, name: "บาเจาะ", nameEn: "Bacho", provinceId: 76 },
  { id: 9604, name: "ยี่งอ", nameEn: "Yi-ngo", provinceId: 76 },
  { id: 9605, name: "ระแงะ", nameEn: "Ra-ngae", provinceId: 76 },
  { id: 9606, name: "รือเสาะ", nameEn: "Rueso", provinceId: 76 },
  { id: 9607, name: "ศรีสาคร", nameEn: "Si Sakhon", provinceId: 76 },
  { id: 9608, name: "แว้ง", nameEn: "Waeng", provinceId: 76 },
  { id: 9609, name: "สุคิริน", nameEn: "Sukhirin", provinceId: 76 },
  { id: 9610, name: "สุไหงโก-ลก", nameEn: "Su-ngai Kolok", provinceId: 76 },
  { id: 9611, name: "สุไหงปาดี", nameEn: "Su-ngai Padi", provinceId: 76 },
  { id: 9612, name: "จะแนะ", nameEn: "Chanae", provinceId: 76 },
  { id: 9613, name: "เจาะไอร้อง", nameEn: "Cho-airong", provinceId: 76 },
];
